//! CMSIS-DSP Integration Driver
//!
//! Provides integration with ARM CMSIS-DSP library for optimized
//! signal processing on Cortex-M processors.

use serde::{Deserialize, Serialize};

/// CMSIS-DSP configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CmsisDspConfig {
    pub core_type: CortexCore,
    pub enable_fft: bool,
    pub enable_filters: bool,
    pub enable_matrix: bool,
    pub enable_statistics: bool,
    pub enable_transform: bool,
    pub fft_sizes: Vec<u32>,
}

impl Default for CmsisDspConfig {
    fn default() -> Self {
        Self {
            core_type: CortexCore::M4,
            enable_fft: true,
            enable_filters: true,
            enable_matrix: true,
            enable_statistics: true,
            enable_transform: true,
            fft_sizes: vec![256, 512, 1024],
        }
    }
}

/// ARM Cortex core type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CortexCore {
    M0,
    M0Plus,
    M3,
    M4,      // With FPU
    M7,      // With double-precision FPU
    M33,     // TrustZone
    M55,     // Helium/MVE
}

impl CortexCore {
    pub fn has_fpu(&self) -> bool {
        !matches!(self, CortexCore::M0 | CortexCore::M0Plus | CortexCore::M3)
    }

    pub fn has_dsp(&self) -> bool {
        matches!(self, CortexCore::M4 | CortexCore::M7 | CortexCore::M33 | CortexCore::M55)
    }

    pub fn has_mve(&self) -> bool {
        matches!(self, CortexCore::M55)
    }
}

/// Generate CMSIS-DSP integration code
pub fn generate_cmsis_dsp_driver(config: &CmsisDspConfig) -> CmsisDspOutput {
    let core_str = format!("{:?}", config.core_type);

    let c_code = format!(r#"/**
 * CMSIS-DSP Integration Driver
 * Auto-generated by NeuroBench
 * Core: {core}
 */

#include <stdint.h>
#include <stdbool.h>

// CMSIS-DSP configuration
#define ARM_MATH_CM{core_num}
#include "arm_math.h"
#include "arm_const_structs.h"

// FFT instances (pre-computed twiddle factors)
{fft_instances}

// ============================================================================
// FFT Functions
// ============================================================================

/**
 * Perform real FFT
 */
void DSP_RFFT_F32(float *input, float *output, uint32_t len) {{
    arm_rfft_fast_instance_f32 instance;
    arm_rfft_fast_init_f32(&instance, len);
    arm_rfft_fast_f32(&instance, input, output, 0);
}}

/**
 * Perform complex FFT
 */
void DSP_CFFT_F32(float *data, uint32_t len) {{
    switch (len) {{
{fft_cases}
        default:
            break;
    }}
}}

/**
 * Calculate magnitude from complex FFT output
 */
void DSP_Magnitude_F32(const float *complex_data, float *magnitude, uint32_t len) {{
    arm_cmplx_mag_f32(complex_data, magnitude, len);
}}

// ============================================================================
// Filter Functions
// ============================================================================

// Biquad IIR filter instance
static arm_biquad_casd_df1_inst_f32 biquad_instance;
static float biquad_state[4];

/**
 * Initialize Biquad filter
 */
void DSP_Biquad_Init(const float *coeffs, uint8_t num_stages) {{
    arm_biquad_cascade_df1_init_f32(&biquad_instance, num_stages, coeffs, biquad_state);
}}

/**
 * Apply Biquad filter
 */
void DSP_Biquad_Process(const float *input, float *output, uint32_t block_size) {{
    arm_biquad_cascade_df1_f32(&biquad_instance, input, output, block_size);
}}

// FIR filter instance
static arm_fir_instance_f32 fir_instance;
static float fir_state[256];  // Adjust based on filter length

/**
 * Initialize FIR filter
 */
void DSP_FIR_Init(const float *coeffs, uint16_t num_taps) {{
    arm_fir_init_f32(&fir_instance, num_taps, coeffs, fir_state, 1);
}}

/**
 * Apply FIR filter
 */
void DSP_FIR_Process(const float *input, float *output, uint32_t block_size) {{
    arm_fir_f32(&fir_instance, input, output, block_size);
}}

// ============================================================================
// Statistics Functions
// ============================================================================

/**
 * Calculate mean
 */
float DSP_Mean_F32(const float *data, uint32_t len) {{
    float result;
    arm_mean_f32(data, len, &result);
    return result;
}}

/**
 * Calculate variance
 */
float DSP_Variance_F32(const float *data, uint32_t len) {{
    float result;
    arm_var_f32(data, len, &result);
    return result;
}}

/**
 * Calculate standard deviation
 */
float DSP_StdDev_F32(const float *data, uint32_t len) {{
    float result;
    arm_std_f32(data, len, &result);
    return result;
}}

/**
 * Find minimum value and index
 */
void DSP_Min_F32(const float *data, uint32_t len, float *min_val, uint32_t *index) {{
    arm_min_f32(data, len, min_val, index);
}}

/**
 * Find maximum value and index
 */
void DSP_Max_F32(const float *data, uint32_t len, float *max_val, uint32_t *index) {{
    arm_max_f32(data, len, max_val, index);
}}

/**
 * Calculate RMS
 */
float DSP_RMS_F32(const float *data, uint32_t len) {{
    float result;
    arm_rms_f32(data, len, &result);
    return result;
}}

// ============================================================================
// Vector Operations
// ============================================================================

/**
 * Vector add
 */
void DSP_VectorAdd_F32(const float *a, const float *b, float *result, uint32_t len) {{
    arm_add_f32(a, b, result, len);
}}

/**
 * Vector multiply
 */
void DSP_VectorMult_F32(const float *a, const float *b, float *result, uint32_t len) {{
    arm_mult_f32(a, b, result, len);
}}

/**
 * Vector scale
 */
void DSP_VectorScale_F32(const float *input, float scale, float *output, uint32_t len) {{
    arm_scale_f32(input, scale, output, len);
}}

/**
 * Dot product
 */
float DSP_DotProduct_F32(const float *a, const float *b, uint32_t len) {{
    float result;
    arm_dot_prod_f32(a, b, len, &result);
    return result;
}}
"#, 
        core = core_str,
        core_num = match config.core_type {
            CortexCore::M0 => "0",
            CortexCore::M0Plus => "0PLUS",
            CortexCore::M3 => "3",
            CortexCore::M4 => "4",
            CortexCore::M7 => "7",
            CortexCore::M33 => "33",
            CortexCore::M55 => "55",
        },
        fft_instances = config.fft_sizes.iter()
            .map(|s| format!("// FFT size {}: use arm_cfft_sR_f32_len{}", s, s))
            .collect::<Vec<_>>()
            .join("\n"),
        fft_cases = config.fft_sizes.iter()
            .map(|s| format!("        case {s}: arm_cfft_f32(&arm_cfft_sR_f32_len{s}, data, 0, 1); break;"))
            .collect::<Vec<_>>()
            .join("\n")
    );

    let rust_code = format!(r#"//! CMSIS-DSP Integration Driver
//! Auto-generated by NeuroBench

/// Cortex core type
pub const CORE: &str = "{core}";

/// FFT sizes supported
pub const FFT_SIZES: &[u32] = &[{fft_sizes}];

/// DSP error types
#[derive(Debug, Clone)]
pub enum DspError {{
    InvalidSize,
    NotSupported,
    BufferTooSmall,
}}

pub type DspResult<T> = Result<T, DspError>;

/// Statistics functions
pub mod stats {{
    /// Calculate mean of a slice
    pub fn mean(data: &[f32]) -> f32 {{
        if data.is_empty() {{
            return 0.0;
        }}
        data.iter().sum::<f32>() / data.len() as f32
    }}
    
    /// Calculate variance
    pub fn variance(data: &[f32]) -> f32 {{
        let m = mean(data);
        if data.is_empty() {{
            return 0.0;
        }}
        data.iter().map(|x| (x - m).powi(2)).sum::<f32>() / data.len() as f32
    }}
    
    /// Calculate standard deviation
    pub fn std_dev(data: &[f32]) -> f32 {{
        variance(data).sqrt()
    }}
    
    /// Calculate RMS
    pub fn rms(data: &[f32]) -> f32 {{
        if data.is_empty() {{
            return 0.0;
        }}
        (data.iter().map(|x| x * x).sum::<f32>() / data.len() as f32).sqrt()
    }}
    
    /// Find min value and index
    pub fn min(data: &[f32]) -> Option<(f32, usize)> {{
        data.iter()
            .enumerate()
            .min_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
            .map(|(i, &v)| (v, i))
    }}
    
    /// Find max value and index
    pub fn max(data: &[f32]) -> Option<(f32, usize)> {{
        data.iter()
            .enumerate()
            .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
            .map(|(i, &v)| (v, i))
    }}
}}

/// Vector operations
pub mod vector {{
    /// Vector add
    pub fn add(a: &[f32], b: &[f32], result: &mut [f32]) {{
        for ((r, x), y) in result.iter_mut().zip(a.iter()).zip(b.iter()) {{
            *r = x + y;
        }}
    }}
    
    /// Vector multiply
    pub fn mult(a: &[f32], b: &[f32], result: &mut [f32]) {{
        for ((r, x), y) in result.iter_mut().zip(a.iter()).zip(b.iter()) {{
            *r = x * y;
        }}
    }}
    
    /// Vector scale
    pub fn scale(input: &[f32], scale: f32, output: &mut [f32]) {{
        for (o, i) in output.iter_mut().zip(input.iter()) {{
            *o = i * scale;
        }}
    }}
    
    /// Dot product
    pub fn dot(a: &[f32], b: &[f32]) -> f32 {{
        a.iter().zip(b.iter()).map(|(x, y)| x * y).sum()
    }}
}}
"#, 
        core = core_str,
        fft_sizes = config.fft_sizes.iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .join(", ")
    );

    CmsisDspOutput { c_code, rust_code }
}

/// CMSIS-DSP driver output
pub struct CmsisDspOutput {
    pub c_code: String,
    pub rust_code: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cortex_core_features() {
        assert!(CortexCore::M4.has_fpu());
        assert!(!CortexCore::M0.has_fpu());
        assert!(CortexCore::M55.has_mve());
    }

    #[test]
    fn test_cmsis_dsp_generation() {
        let config = CmsisDspConfig::default();
        let output = generate_cmsis_dsp_driver(&config);
        assert!(output.c_code.contains("DSP_RFFT_F32"));
        assert!(output.rust_code.contains("stats"));
    }
}

