//! TinyML/Neural Network Inference Driver
//!
//! Provides neural network inference for embedded systems.
//! Supports quantized models compatible with TensorFlow Lite Micro.

use serde::{Deserialize, Serialize};

/// Neural network configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NnConfig {
    pub framework: NnFramework,
    pub quantization: Quantization,
    pub use_cmsis_nn: bool,
    pub arena_size_kb: u32,
    pub tensor_arena_alignment: u32,
}

impl Default for NnConfig {
    fn default() -> Self {
        Self {
            framework: NnFramework::TfliteMicro,
            quantization: Quantization::Int8,
            use_cmsis_nn: true,
            arena_size_kb: 64,
            tensor_arena_alignment: 16,
        }
    }
}

/// NN framework
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NnFramework {
    TfliteMicro,     // TensorFlow Lite Micro
    CmsisNn,         // ARM CMSIS-NN only
    CustomQuant,     // Custom quantized inference
}

/// Quantization type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Quantization {
    Float32,    // Full precision
    Float16,    // Half precision
    Int8,       // 8-bit quantized
    Int4,       // 4-bit quantized
}

/// Layer types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LayerType {
    FullyConnected,
    Conv2D,
    DepthwiseConv2D,
    MaxPool2D,
    AveragePool2D,
    Softmax,
    Relu,
    Relu6,
    Add,
    Reshape,
}

/// Generate NN inference driver code
pub fn generate_nn_driver(config: &NnConfig) -> NnOutput {
    let framework_str = format!("{:?}", config.framework);
    let arena_bytes = config.arena_size_kb * 1024;

    let c_code = format!(r#"/**
 * TinyML Inference Driver
 * Auto-generated by NeuroBench
 * Framework: {framework}
 */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#ifdef USE_TFLITE_MICRO
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"
#endif

#ifdef USE_CMSIS_NN
#include "arm_nnfunctions.h"
#endif

// Tensor arena configuration
#define TENSOR_ARENA_SIZE {arena_size}
static uint8_t tensor_arena[TENSOR_ARENA_SIZE] __attribute__((aligned({alignment})));

// Status codes
typedef enum {{
    NN_OK = 0,
    NN_ERROR_INIT,
    NN_ERROR_MEMORY,
    NN_ERROR_INVOKE,
    NN_ERROR_MODEL,
}} NnResult;

// Model info
typedef struct {{
    const uint8_t *model_data;
    size_t model_size;
    uint8_t *input_tensor;
    size_t input_size;
    uint8_t *output_tensor;
    size_t output_size;
    void *interpreter;
}} NnModel;

static NnModel current_model;

// Function prototypes
NnResult NN_Init(const uint8_t *model_data, size_t model_size);
NnResult NN_Invoke(void);
uint8_t* NN_GetInputBuffer(size_t *size);
uint8_t* NN_GetOutputBuffer(size_t *size);
void NN_Deinit(void);

// Quantization helpers
int8_t NN_QuantizeFloat(float value, float scale, int32_t zero_point);
float NN_DequantizeInt8(int8_t value, float scale, int32_t zero_point);

/**
 * Initialize model
 */
NnResult NN_Init(const uint8_t *model_data, size_t model_size) {{
    current_model.model_data = model_data;
    current_model.model_size = model_size;
    
#ifdef USE_TFLITE_MICRO
    // Get model from buffer
    const tflite::Model* model = tflite::GetModel(model_data);
    if (model->version() != TFLITE_SCHEMA_VERSION) {{
        return NN_ERROR_MODEL;
    }}
    
    // Create op resolver (add ops as needed)
    static tflite::MicroMutableOpResolver<10> resolver;
    resolver.AddFullyConnected();
    resolver.AddConv2D();
    resolver.AddDepthwiseConv2D();
    resolver.AddMaxPool2D();
    resolver.AddSoftmax();
    resolver.AddRelu();
    resolver.AddReshape();
    
    // Create interpreter
    static tflite::MicroInterpreter interpreter(model, resolver, tensor_arena, 
                                                 TENSOR_ARENA_SIZE, nullptr);
    if (interpreter.AllocateTensors() != kTfLiteOk) {{
        return NN_ERROR_MEMORY;
    }}
    
    current_model.input_tensor = interpreter.input(0)->data.uint8;
    current_model.input_size = interpreter.input(0)->bytes;
    current_model.output_tensor = interpreter.output(0)->data.uint8;
    current_model.output_size = interpreter.output(0)->bytes;
    current_model.interpreter = (void*)&interpreter;
#endif
    
    return NN_OK;
}}

/**
 * Run inference
 */
NnResult NN_Invoke(void) {{
#ifdef USE_TFLITE_MICRO
    tflite::MicroInterpreter* interp = (tflite::MicroInterpreter*)current_model.interpreter;
    if (interp->Invoke() != kTfLiteOk) {{
        return NN_ERROR_INVOKE;
    }}
#endif
    return NN_OK;
}}

/**
 * Get input buffer pointer
 */
uint8_t* NN_GetInputBuffer(size_t *size) {{
    if (size) *size = current_model.input_size;
    return current_model.input_tensor;
}}

/**
 * Get output buffer pointer
 */
uint8_t* NN_GetOutputBuffer(size_t *size) {{
    if (size) *size = current_model.output_size;
    return current_model.output_tensor;
}}

/**
 * Quantize float to int8
 */
int8_t NN_QuantizeFloat(float value, float scale, int32_t zero_point) {{
    int32_t quantized = (int32_t)(value / scale) + zero_point;
    if (quantized < -128) quantized = -128;
    if (quantized > 127) quantized = 127;
    return (int8_t)quantized;
}}

/**
 * Dequantize int8 to float
 */
float NN_DequantizeInt8(int8_t value, float scale, int32_t zero_point) {{
    return ((int32_t)value - zero_point) * scale;
}}

// ============================================================================
// CMSIS-NN Layer Implementations
// ============================================================================

#ifdef USE_CMSIS_NN
/**
 * Fully connected layer (int8)
 */
NnResult NN_FullyConnected_Int8(const int8_t *input, const int8_t *weights,
                                 const int32_t *bias, int8_t *output,
                                 int32_t input_offset, int32_t output_offset,
                                 int32_t output_mult, int32_t output_shift,
                                 int32_t input_size, int32_t output_size) {{
    cmsis_nn_context ctx = {{NULL, 0}};
    cmsis_nn_fc_params fc_params;
    fc_params.input_offset = input_offset;
    fc_params.output_offset = output_offset;
    fc_params.filter_offset = 0;
    fc_params.activation.min = -128;
    fc_params.activation.max = 127;
    
    cmsis_nn_per_tensor_quant_params quant_params;
    quant_params.multiplier = output_mult;
    quant_params.shift = output_shift;
    
    cmsis_nn_dims input_dims = {{1, 1, 1, input_size}};
    cmsis_nn_dims filter_dims = {{1, 1, input_size, output_size}};
    cmsis_nn_dims bias_dims = {{1, 1, 1, output_size}};
    cmsis_nn_dims output_dims = {{1, 1, 1, output_size}};
    
    arm_cmsis_nn_status status = arm_fully_connected_s8(
        &ctx, &fc_params, &quant_params,
        &input_dims, input,
        &filter_dims, weights,
        &bias_dims, bias,
        &output_dims, output);
    
    return (status == ARM_CMSIS_NN_SUCCESS) ? NN_OK : NN_ERROR_INVOKE;
}}

/**
 * Softmax (int8)
 */
void NN_Softmax_Int8(const int8_t *input, int8_t *output, int32_t size,
                      int32_t mult, int32_t shift, int32_t diff_min) {{
    arm_softmax_s8(input, size, mult, shift, diff_min, output);
}}
#endif
"#, 
        framework = framework_str,
        arena_size = arena_bytes,
        alignment = config.tensor_arena_alignment
    );

    let rust_code = format!(r#"//! TinyML Inference Driver
//! Auto-generated by NeuroBench

/// Tensor arena size
pub const ARENA_SIZE: usize = {arena_kb} * 1024;

/// NN error types
#[derive(Debug, Clone)]
pub enum NnError {{
    InitFailed,
    OutOfMemory,
    InvokeFailed,
    InvalidModel,
    InputSizeMismatch,
}}

pub type NnResult<T> = Result<T, NnError>;

/// Quantization parameters
#[derive(Debug, Clone, Copy)]
pub struct QuantParams {{
    pub scale: f32,
    pub zero_point: i32,
}}

impl QuantParams {{
    pub fn quantize(&self, value: f32) -> i8 {{
        let q = (value / self.scale) as i32 + self.zero_point;
        q.clamp(-128, 127) as i8
    }}
    
    pub fn dequantize(&self, value: i8) -> f32 {{
        (value as i32 - self.zero_point) as f32 * self.scale
    }}
}}

/// Simple dense layer (for testing)
pub struct DenseLayer {{
    weights: Vec<i8>,
    bias: Vec<i32>,
    input_size: usize,
    output_size: usize,
    input_params: QuantParams,
    output_params: QuantParams,
}}

impl DenseLayer {{
    pub fn new(weights: Vec<i8>, bias: Vec<i32>, input_size: usize, output_size: usize) -> Self {{
        Self {{
            weights,
            bias,
            input_size,
            output_size,
            input_params: QuantParams {{ scale: 0.00390625, zero_point: 0 }},
            output_params: QuantParams {{ scale: 0.00390625, zero_point: 0 }},
        }}
    }}
    
    pub fn forward(&self, input: &[i8]) -> Vec<i8> {{
        let mut output = vec![0i8; self.output_size];
        
        for o in 0..self.output_size {{
            let mut acc: i32 = self.bias[o];
            for i in 0..self.input_size {{
                acc += (input[i] as i32) * (self.weights[o * self.input_size + i] as i32);
            }}
            // Requantize to output scale
            let scaled = acc >> 8; // Simplified scaling
            output[o] = scaled.clamp(-128, 127) as i8;
        }}
        
        output
    }}
}}

/// ReLU activation (int8)
pub fn relu_i8(data: &mut [i8]) {{
    for x in data.iter_mut() {{
        if *x < 0 {{
            *x = 0;
        }}
    }}
}}

/// Softmax (float output for final layer)
pub fn softmax(input: &[i8], params: &QuantParams) -> Vec<f32> {{
    let floats: Vec<f32> = input.iter().map(|&x| params.dequantize(x)).collect();
    let max = floats.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
    let exp_sum: f32 = floats.iter().map(|x| (x - max).exp()).sum();
    floats.iter().map(|x| (x - max).exp() / exp_sum).collect()
}}

/// Model inference trait
pub trait NnModel {{
    fn init(&mut self) -> NnResult<()>;
    fn input_size(&self) -> usize;
    fn output_size(&self) -> usize;
    fn invoke(&mut self, input: &[i8]) -> NnResult<Vec<i8>>;
}}
"#, arena_kb = config.arena_size_kb);

    NnOutput { c_code, rust_code }
}

/// NN driver output
pub struct NnOutput {
    pub c_code: String,
    pub rust_code: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_nn_config_default() {
        let config = NnConfig::default();
        assert!(config.use_cmsis_nn);
        assert_eq!(config.quantization, Quantization::Int8);
    }

    #[test]
    fn test_nn_generation() {
        let config = NnConfig::default();
        let output = generate_nn_driver(&config);
        assert!(output.c_code.contains("NN_Init"));
        assert!(output.rust_code.contains("QuantParams"));
    }
}

