//! Enhanced Code Generation - Guards, Actions, HAL Templates, Multi-File Export
//!
//! Industrial-grade code generation for embedded FSM designs.

use serde::{Deserialize, Serialize};

/// HAL Framework targets
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HalFramework {
    /// STM32 HAL
    Stm32Hal,
    /// STM32 Low-Level
    Stm32Ll,
    /// ESP-IDF
    EspIdf,
    /// Arduino
    Arduino,
    /// Zephyr RTOS
    Zephyr,
    /// Bare Metal
    BareMetal,
}

/// Generated file for multi-file export
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
    pub file_type: FileType,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileType {
    Header,
    Source,
    Config,
    Makefile,
    Cmake,
}

/// FSM transition with guard and action
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnhancedTransition {
    pub from: String,
    pub to: String,
    pub event: Option<String>,
    pub guard: Option<String>,
    pub action: Option<String>,
}

/// Enhanced FSM state with entry/exit actions
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnhancedState {
    pub id: String,
    pub name: String,
    pub entry_action: Option<String>,
    pub exit_action: Option<String>,
    pub is_initial: bool,
    pub is_final: bool,
}

/// Enhanced code generation context
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnhancedCodeGenContext {
    pub project_name: String,
    pub states: Vec<EnhancedState>,
    pub transitions: Vec<EnhancedTransition>,
    pub hal: HalFramework,
    pub mcu: String,
    pub use_rtos: bool,
}

/// Generate enhanced C code with guards and actions
pub fn generate_enhanced_c(ctx: &EnhancedCodeGenContext) -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    
    // Header file
    let header = generate_c_header(ctx);
    files.push(GeneratedFile {
        path: format!("{}_fsm.h", ctx.project_name.to_lowercase()),
        content: header,
        file_type: FileType::Header,
    });
    
    // Source file
    let source = generate_c_source(ctx);
    files.push(GeneratedFile {
        path: format!("{}_fsm.c", ctx.project_name.to_lowercase()),
        content: source,
        file_type: FileType::Source,
    });
    
    // HAL config header if needed
    if ctx.hal != HalFramework::BareMetal {
        let hal_config = generate_hal_config(ctx);
        files.push(GeneratedFile {
            path: format!("{}_hal_config.h", ctx.project_name.to_lowercase()),
            content: hal_config,
            file_type: FileType::Config,
        });
    }
    
    files
}

fn generate_c_header(ctx: &EnhancedCodeGenContext) -> String {
    let guard = ctx.project_name.to_uppercase().replace(" ", "_");
    let states: Vec<_> = ctx.states.iter()
        .map(|s| format!("    STATE_{}", s.name.to_uppercase()))
        .collect();
    
    let events: Vec<_> = ctx.transitions.iter()
        .filter_map(|t| t.event.as_ref())
        .map(|e| format!("    EVENT_{}", e.to_uppercase()))
        .collect::<std::collections::HashSet<_>>()
        .into_iter()
        .collect();

    format!(r#"/**
 * {name} FSM - Generated by NeuroBench
 * Target: {mcu} / {hal:?}
 */

#ifndef {guard}_FSM_H
#define {guard}_FSM_H

#include <stdint.h>
#include <stdbool.h>

// States
typedef enum {{
{states},
    STATE_COUNT
}} {name}_State;

// Events
typedef enum {{
{events},
    EVENT_COUNT
}} {name}_Event;

// FSM Context
typedef struct {{
    {name}_State current_state;
    {name}_State previous_state;
    uint32_t state_entry_time;
    void* user_data;
}} {name}_FSM;

// API
void {name}_fsm_init({name}_FSM* fsm, void* user_data);
void {name}_fsm_process({name}_FSM* fsm, {name}_Event event);
{name}_State {name}_fsm_get_state(const {name}_FSM* fsm);
const char* {name}_state_to_string({name}_State state);
const char* {name}_event_to_string({name}_Event event);

// Guard declarations (implement in user code)
{guards}

// Action declarations (implement in user code)
{actions}

#endif // {guard}_FSM_H
"#,
        name = ctx.project_name,
        mcu = ctx.mcu,
        hal = ctx.hal,
        guard = guard,
        states = states.join(",\n"),
        events = events.join(",\n"),
        guards = generate_guard_declarations(ctx),
        actions = generate_action_declarations(ctx),
    )
}

fn generate_c_source(ctx: &EnhancedCodeGenContext) -> String {
    let initial_state = ctx.states.iter()
        .find(|s| s.is_initial)
        .map(|s| format!("STATE_{}", s.name.to_uppercase()))
        .unwrap_or_else(|| "STATE_IDLE".to_string());

    format!(r#"/**
 * {name} FSM Implementation
 * Generated by NeuroBench
 */

#include "{name_lower}_fsm.h"
#include <string.h>

// State entry/exit handlers
{entry_exit_handlers}

// Transition table
static void process_transitions({name}_FSM* fsm, {name}_Event event) {{
    switch (fsm->current_state) {{
{transition_cases}
        default:
            break;
    }}
}}

void {name}_fsm_init({name}_FSM* fsm, void* user_data) {{
    memset(fsm, 0, sizeof({name}_FSM));
    fsm->current_state = {initial};
    fsm->previous_state = {initial};
    fsm->user_data = user_data;
    
    // Call entry action for initial state
    {name}_on_enter_{initial_lower}(fsm);
}}

void {name}_fsm_process({name}_FSM* fsm, {name}_Event event) {{
    {name}_State old_state = fsm->current_state;
    process_transitions(fsm, event);
    
    if (old_state != fsm->current_state) {{
        fsm->previous_state = old_state;
        // Exit old state
        switch (old_state) {{
{exit_cases}
            default: break;
        }}
        // Enter new state
        switch (fsm->current_state) {{
{entry_cases}
            default: break;
        }}
    }}
}}

{name}_State {name}_fsm_get_state(const {name}_FSM* fsm) {{
    return fsm->current_state;
}}

const char* {name}_state_to_string({name}_State state) {{
    static const char* names[] = {{
{state_names}
    }};
    return (state < STATE_COUNT) ? names[state] : "UNKNOWN";
}}

const char* {name}_event_to_string({name}_Event event) {{
    static const char* names[] = {{
{event_names}
    }};
    return (event < EVENT_COUNT) ? names[event] : "UNKNOWN";
}}
"#,
        name = ctx.project_name,
        name_lower = ctx.project_name.to_lowercase(),
        initial = initial_state,
        initial_lower = initial_state.to_lowercase().replace("state_", ""),
        entry_exit_handlers = generate_entry_exit_handlers(ctx),
        transition_cases = generate_transition_cases(ctx),
        exit_cases = generate_exit_cases(ctx),
        entry_cases = generate_entry_cases(ctx),
        state_names = ctx.states.iter()
            .map(|s| format!("        \"{}\"", s.name))
            .collect::<Vec<_>>()
            .join(",\n"),
        event_names = ctx.transitions.iter()
            .filter_map(|t| t.event.as_ref())
            .collect::<std::collections::HashSet<_>>()
            .iter()
            .map(|e| format!("        \"{}\"", e))
            .collect::<Vec<_>>()
            .join(",\n"),
    )
}

fn generate_guard_declarations(ctx: &EnhancedCodeGenContext) -> String {
    ctx.transitions.iter()
        .filter_map(|t| t.guard.as_ref())
        .collect::<std::collections::HashSet<_>>()
        .iter()
        .map(|g| format!("bool guard_{}(const {}_FSM* fsm);", g, ctx.project_name))
        .collect::<Vec<_>>()
        .join("\n")
}

fn generate_action_declarations(ctx: &EnhancedCodeGenContext) -> String {
    let mut actions = std::collections::HashSet::new();
    
    for t in &ctx.transitions {
        if let Some(ref a) = t.action {
            actions.insert(a.clone());
        }
    }
    for s in &ctx.states {
        if let Some(ref a) = s.entry_action {
            actions.insert(a.clone());
        }
        if let Some(ref a) = s.exit_action {
            actions.insert(a.clone());
        }
    }
    
    actions.iter()
        .map(|a| format!("void action_{}({}_FSM* fsm);", a, ctx.project_name))
        .collect::<Vec<_>>()
        .join("\n")
}

fn generate_entry_exit_handlers(ctx: &EnhancedCodeGenContext) -> String {
    ctx.states.iter()
        .map(|s| {
            let entry = s.entry_action.as_ref()
                .map(|a| format!("action_{}(fsm);", a))
                .unwrap_or_default();
            let exit = s.exit_action.as_ref()
                .map(|a| format!("action_{}(fsm);", a))
                .unwrap_or_default();
            
            format!(r#"
__attribute__((weak)) void {name}_on_enter_{state}({name}_FSM* fsm) {{
    {entry}
}}

__attribute__((weak)) void {name}_on_exit_{state}({name}_FSM* fsm) {{
    {exit}
}}"#,
                name = ctx.project_name,
                state = s.name.to_lowercase(),
                entry = entry,
                exit = exit,
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn generate_transition_cases(ctx: &EnhancedCodeGenContext) -> String {
    let mut cases_by_state: std::collections::HashMap<String, Vec<String>> = std::collections::HashMap::new();
    
    for t in &ctx.transitions {
        let event_check = t.event.as_ref()
            .map(|e| format!("if (event == EVENT_{}) ", e.to_uppercase()))
            .unwrap_or_default();
        
        let guard_check = t.guard.as_ref()
            .map(|g| format!("&& guard_{}(fsm) ", g))
            .unwrap_or_default();
        
        let action_call = t.action.as_ref()
            .map(|a| format!("action_{}(fsm); ", a))
            .unwrap_or_default();
        
        let transition = format!(
            "{}{}{{ {}fsm->current_state = STATE_{}; }}",
            event_check,
            guard_check,
            action_call,
            t.to.to_uppercase()
        );
        
        cases_by_state.entry(t.from.clone())
            .or_default()
            .push(transition);
    }
    
    cases_by_state.iter()
        .map(|(state, transitions)| {
            format!(
                "        case STATE_{}:\n            {}\n            break;",
                state.to_uppercase(),
                transitions.join("\n            ")
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn generate_exit_cases(ctx: &EnhancedCodeGenContext) -> String {
    ctx.states.iter()
        .map(|s| format!(
            "            case STATE_{}: {}_on_exit_{}(fsm); break;",
            s.name.to_uppercase(),
            ctx.project_name,
            s.name.to_lowercase()
        ))
        .collect::<Vec<_>>()
        .join("\n")
}

fn generate_entry_cases(ctx: &EnhancedCodeGenContext) -> String {
    ctx.states.iter()
        .map(|s| format!(
            "            case STATE_{}: {}_on_enter_{}(fsm); break;",
            s.name.to_uppercase(),
            ctx.project_name,
            s.name.to_lowercase()
        ))
        .collect::<Vec<_>>()
        .join("\n")
}

fn generate_hal_config(ctx: &EnhancedCodeGenContext) -> String {
    match ctx.hal {
        HalFramework::Stm32Hal => generate_stm32_hal_config(ctx),
        HalFramework::EspIdf => generate_esp_idf_config(ctx),
        HalFramework::Arduino => generate_arduino_config(ctx),
        _ => String::new(),
    }
}

fn generate_stm32_hal_config(ctx: &EnhancedCodeGenContext) -> String {
    format!(r#"/**
 * STM32 HAL Configuration for {name}
 * Target MCU: {mcu}
 */

#ifndef {guard}_HAL_CONFIG_H
#define {guard}_HAL_CONFIG_H

#include "stm32f4xx_hal.h"  // Adjust for your MCU family

// Timer for state timing
#define FSM_TIMER_INSTANCE  TIM2
#define FSM_TIMER_IRQn      TIM2_IRQn

// Debug UART
#define FSM_DEBUG_UART      huart2

// GPIO for status LED
#define FSM_LED_PORT        GPIOA
#define FSM_LED_PIN         GPIO_PIN_5

// Function prototypes
void FSM_Timer_Init(void);
uint32_t FSM_GetTick(void);
void FSM_Debug_Print(const char* msg);

#endif // {guard}_HAL_CONFIG_H
"#,
        name = ctx.project_name,
        mcu = ctx.mcu,
        guard = ctx.project_name.to_uppercase().replace(" ", "_"),
    )
}

fn generate_esp_idf_config(ctx: &EnhancedCodeGenContext) -> String {
    format!(r#"/**
 * ESP-IDF Configuration for {name}
 * Target: {mcu}
 */

#ifndef {guard}_HAL_CONFIG_H
#define {guard}_HAL_CONFIG_H

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/gpio.h"
#include "esp_log.h"

#define FSM_TAG "{name}"
#define FSM_LED_GPIO GPIO_NUM_2

// FreeRTOS task config
#define FSM_TASK_STACK_SIZE 4096
#define FSM_TASK_PRIORITY 5

void fsm_task(void *pvParameters);

#endif // {guard}_HAL_CONFIG_H
"#,
        name = ctx.project_name,
        mcu = ctx.mcu,
        guard = ctx.project_name.to_uppercase().replace(" ", "_"),
    )
}

fn generate_arduino_config(ctx: &EnhancedCodeGenContext) -> String {
    format!(r#"/**
 * Arduino Configuration for {name}
 */

#ifndef {guard}_HAL_CONFIG_H
#define {guard}_HAL_CONFIG_H

#include <Arduino.h>

#define FSM_LED_PIN 13
#define FSM_DEBUG_SERIAL Serial
#define FSM_DEBUG_BAUD 115200

void fsm_debug_print(const char* msg);

#endif // {guard}_HAL_CONFIG_H
"#,
        name = ctx.project_name,
        guard = ctx.project_name.to_uppercase().replace(" ", "_"),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_enhanced_codegen() {
        let ctx = EnhancedCodeGenContext {
            project_name: "TrafficLight".to_string(),
            states: vec![
                EnhancedState {
                    id: "1".to_string(),
                    name: "Red".to_string(),
                    entry_action: Some("turn_on_red".to_string()),
                    exit_action: Some("turn_off_red".to_string()),
                    is_initial: true,
                    is_final: false,
                },
                EnhancedState {
                    id: "2".to_string(),
                    name: "Green".to_string(),
                    entry_action: Some("turn_on_green".to_string()),
                    exit_action: Some("turn_off_green".to_string()),
                    is_initial: false,
                    is_final: false,
                },
            ],
            transitions: vec![
                EnhancedTransition {
                    from: "Red".to_string(),
                    to: "Green".to_string(),
                    event: Some("TIMER".to_string()),
                    guard: Some("is_safe".to_string()),
                    action: Some("log_transition".to_string()),
                },
            ],
            hal: HalFramework::Stm32Hal,
            mcu: "STM32F401RE".to_string(),
            use_rtos: false,
        };

        let files = generate_enhanced_c(&ctx);
        assert_eq!(files.len(), 3);
        assert!(files[0].content.contains("STATE_RED"));
        assert!(files[1].content.contains("guard_is_safe"));
    }
}
