// GPIO Driver Generator
// Generates GPIO drivers for various MCU architectures

use super::templates::*;

/// Generate GPIO driver code
pub fn generate_gpio_driver(config: &GpioConfig, arch: &McuArch, lang: &DriverLanguage) -> DriverOutput {
    match lang {
        DriverLanguage::C => generate_gpio_c(config, arch),
        DriverLanguage::Cpp => generate_gpio_cpp(config, arch),
        DriverLanguage::Rust => generate_gpio_rust(config, arch),
        DriverLanguage::Ada => generate_gpio_ada(config, arch),
        DriverLanguage::Assembly => generate_gpio_asm(config, arch),
        DriverLanguage::MicroPython => generate_gpio_micropython(config, arch),
        DriverLanguage::Zig => generate_gpio_zig(config, arch),
    }
}

fn generate_gpio_c(config: &GpioConfig, _arch: &McuArch) -> DriverOutput {
    let port = &config.port;
    let pin = config.pin;
    let pin_name = format!("P{}{}", port, pin);
    
    let mode_str = match config.mode {
        GpioMode::Input => "GPIO_MODE_INPUT",
        GpioMode::Output => "GPIO_MODE_OUTPUT_PP",
        GpioMode::AlternateFunction => "GPIO_MODE_AF_PP",
        GpioMode::Analog => "GPIO_MODE_ANALOG",
    };
    
    let pull_str = match config.pull {
        GpioPull::None => "GPIO_NOPULL",
        GpioPull::Up | GpioPull::PullUp => "GPIO_PULLUP",
        GpioPull::Down | GpioPull::PullDown => "GPIO_PULLDOWN",
    };
    
    let speed_str = match config.speed {
        GpioSpeed::Low => "GPIO_SPEED_FREQ_LOW",
        GpioSpeed::Medium => "GPIO_SPEED_FREQ_MEDIUM",
        GpioSpeed::High => "GPIO_SPEED_FREQ_HIGH",
        GpioSpeed::VeryHigh => "GPIO_SPEED_FREQ_VERY_HIGH",
    };

    let header = format!(r#"/**
 * GPIO Driver for {pin_name}
 * Auto-generated by NeuroBench
 */

#ifndef GPIO_{port}{pin}_DRIVER_H
#define GPIO_{port}{pin}_DRIVER_H

#include <stdint.h>
#include <stdbool.h>

// Pin definition
#define {pin_name}_PORT GPIO{port}
#define {pin_name}_PIN  GPIO_PIN_{pin}

// Function prototypes
void {pin_name}_Init(void);
void {pin_name}_Write(bool state);
bool {pin_name}_Read(void);
void {pin_name}_Toggle(void);

#endif // GPIO_{port}{pin}_DRIVER_H
"#);

    let source = format!(r#"/**
 * GPIO Driver for {pin_name}
 * Auto-generated by NeuroBench
 */

#include "gpio_{port}{pin}_driver.h"
#include "stm32f4xx_hal.h"

/**
 * Initialize GPIO pin {pin_name}
 */
void {pin_name}_Init(void) {{
    // Enable GPIO clock
    __HAL_RCC_GPIO{port}_CLK_ENABLE();
    
    GPIO_InitTypeDef GPIO_InitStruct = {{0}};
    
    GPIO_InitStruct.Pin = {pin_name}_PIN;
    GPIO_InitStruct.Mode = {mode_str};
    GPIO_InitStruct.Pull = {pull_str};
    GPIO_InitStruct.Speed = {speed_str};
    
    HAL_GPIO_Init({pin_name}_PORT, &GPIO_InitStruct);
}}

/**
 * Write to GPIO pin
 * @param state: true = HIGH, false = LOW
 */
void {pin_name}_Write(bool state) {{
    HAL_GPIO_WritePin({pin_name}_PORT, {pin_name}_PIN, 
                      state ? GPIO_PIN_SET : GPIO_PIN_RESET);
}}

/**
 * Read GPIO pin state
 * @return true if HIGH, false if LOW
 */
bool {pin_name}_Read(void) {{
    return HAL_GPIO_ReadPin({pin_name}_PORT, {pin_name}_PIN) == GPIO_PIN_SET;
}}

/**
 * Toggle GPIO pin
 */
void {pin_name}_Toggle(void) {{
    HAL_GPIO_TogglePin({pin_name}_PORT, {pin_name}_PIN);
}}
"#);

    let example = format!(r#"/**
 * Example usage of {pin_name} GPIO driver
 */

#include "gpio_{port}{pin}_driver.h"

int main(void) {{
    // Initialize HAL
    HAL_Init();
    
    // Initialize GPIO pin
    {pin_name}_Init();
    
    // Example: Blink LED
    while (1) {{
        {pin_name}_Toggle();
        HAL_Delay(500);  // 500ms delay
    }}
    
    return 0;
}}
"#);

    DriverOutput {
        header_file: Some(header),
        source_file: source,
        example_file: Some(example),
        peripheral_type: PeripheralType::GPIO,
    }
}

fn generate_gpio_cpp(config: &GpioConfig, _arch: &McuArch) -> DriverOutput {
    let port = &config.port;
    let pin = config.pin;
    let class_name = format!("Gpio{}{}", port, pin);

    let header = format!(r#"/**
 * GPIO Driver Class for P{port}{pin}
 * Auto-generated by NeuroBench
 */

#pragma once

#include <cstdint>

class {class_name} {{
public:
    enum class Mode {{ Input, Output, AlternateFunction, Analog }};
    enum class Pull {{ None, Up, Down }};
    
    static void init(Mode mode = Mode::Output, Pull pull = Pull::None);
    static void write(bool state);
    static bool read();
    static void toggle();
    
private:
    static constexpr uint8_t PORT = '{port}';
    static constexpr uint8_t PIN = {pin};
}};
"#);

    let source = format!(r#"/**
 * GPIO Driver Class Implementation
 * Auto-generated by NeuroBench
 */

#include "{class_name}.hpp"
#include "stm32f4xx_hal.h"

void {class_name}::init(Mode mode, Pull pull) {{
    __HAL_RCC_GPIO{port}_CLK_ENABLE();
    
    GPIO_InitTypeDef init{{}};
    init.Pin = GPIO_PIN_{pin};
    init.Mode = (mode == Mode::Output) ? GPIO_MODE_OUTPUT_PP : GPIO_MODE_INPUT;
    init.Pull = (pull == Pull::Up) ? GPIO_PULLUP : 
                (pull == Pull::Down) ? GPIO_PULLDOWN : GPIO_NOPULL;
    init.Speed = GPIO_SPEED_FREQ_HIGH;
    
    HAL_GPIO_Init(GPIO{port}, &init);
}}

void {class_name}::write(bool state) {{
    HAL_GPIO_WritePin(GPIO{port}, GPIO_PIN_{pin}, 
                      state ? GPIO_PIN_SET : GPIO_PIN_RESET);
}}

bool {class_name}::read() {{
    return HAL_GPIO_ReadPin(GPIO{port}, GPIO_PIN_{pin}) == GPIO_PIN_SET;
}}

void {class_name}::toggle() {{
    HAL_GPIO_TogglePin(GPIO{port}, GPIO_PIN_{pin});
}}
"#);

    DriverOutput {
        header_file: Some(header),
        source_file: source,
        example_file: None,
        peripheral_type: PeripheralType::GPIO,
    }
}

fn generate_gpio_rust(config: &GpioConfig, _arch: &McuArch) -> DriverOutput {
    let port_lower = config.port.to_lowercase();
    let port_upper = config.port.to_uppercase();
    let pin = config.pin;

    let source = format!(
r#"//! GPIO Driver for P{port_upper}{pin}
//! Auto-generated by NeuroBench

use embedded_hal::digital::v2::{{OutputPin, InputPin, ToggleableOutputPin}};

/// GPIO Pin P{port_upper}{pin} wrapper
pub struct Gpio{port_upper}{pin}<MODE> {{
    pin: stm32f4xx_hal::gpio::gpio{port_lower}::P{port_upper}{pin}<MODE>,
}}

impl<MODE> Gpio{port_upper}{pin}<MODE> {{
    /// Create new GPIO wrapper
    pub fn new(pin: stm32f4xx_hal::gpio::gpio{port_lower}::P{port_upper}{pin}<MODE>) -> Self {{
        Self {{ pin }}
    }}
}}

impl Gpio{port_upper}{pin}<stm32f4xx_hal::gpio::Output<stm32f4xx_hal::gpio::PushPull>> {{
    /// Set pin high
    pub fn set_high(&mut self) {{
        self.pin.set_high().ok();
    }}
    
    /// Set pin low
    pub fn set_low(&mut self) {{
        self.pin.set_low().ok();
    }}
    
    /// Toggle pin state
    pub fn toggle(&mut self) {{
        self.pin.toggle().ok();
    }}
}}

impl Gpio{port_upper}{pin}<stm32f4xx_hal::gpio::Input<stm32f4xx_hal::gpio::Floating>> {{
    /// Read pin state
    pub fn is_high(&self) -> bool {{
        self.pin.is_high().unwrap_or(false)
    }}
    
    /// Read pin state
    pub fn is_low(&self) -> bool {{
        self.pin.is_low().unwrap_or(false)
    }}
}}
"#, port_upper = port_upper, port_lower = port_lower, pin = pin);

    DriverOutput {
        header_file: None,
        source_file: source,
        example_file: None,
        peripheral_type: PeripheralType::GPIO,
    }
}

/// Generate Ada/SPARK GPIO driver
fn generate_gpio_ada(config: &GpioConfig, _arch: &McuArch) -> DriverOutput {
    let port = &config.port;
    let pin = config.pin;
    let package_name = format!("GPIO_{}{}", port, pin);

    let port_base: u32 = match port.as_str() {
        "A" => 0x4002_0000,
        "B" => 0x4002_0400,
        "C" => 0x4002_0800,
        "D" => 0x4002_0C00,
        "E" => 0x4002_1000,
        _ => 0x4002_0000,
    };
    let pin_mask: u16 = 1 << pin;

    let spec = format!(r#"--  GPIO Driver for P{port}{pin}
--  Auto-generated by NeuroBench
--  SPARK-compatible GPIO abstraction

pragma Ada_2012;
pragma SPARK_Mode (On);

with Interfaces;  use Interfaces;

package {package_name}
  with Preelaborate
is
   Port_Base : constant Unsigned_32 := 16#{port_base:08X}#;
   Pin_Mask  : constant Unsigned_16 := 16#{pin_mask:04X}#;

   type Pin_State is (Low, High);

   procedure Initialize with Global => null;
   procedure Write (State : Pin_State) with Global => null;
   function Read return Pin_State with Global => null;
   procedure Toggle_Pin with Global => null;

end {package_name};
"#, port = port, pin = pin, package_name = package_name, 
    port_base = port_base, pin_mask = pin_mask);

    let body = format!(r#"--  GPIO Driver Implementation for P{port}{pin}
pragma Ada_2012;
pragma SPARK_Mode (On);

with System.Storage_Elements; use System.Storage_Elements;

package body {package_name} is
   MODER_Offset : constant := 16#00#;
   ODR_Offset   : constant := 16#14#;
   IDR_Offset   : constant := 16#10#;

   procedure Initialize is
      MODER : Unsigned_32 with Address => To_Address (Integer_Address (Port_Base)), Volatile;
   begin
      MODER := (MODER and not (3 * 2 ** ({pin} * 2))) or (1 * 2 ** ({pin} * 2));
   end Initialize;

   procedure Write (State : Pin_State) is
      ODR : Unsigned_32 with Address => To_Address (Integer_Address (Port_Base) + ODR_Offset), Volatile;
   begin
      case State is
         when High => ODR := ODR or Unsigned_32 (Pin_Mask);
         when Low  => ODR := ODR and not Unsigned_32 (Pin_Mask);
      end case;
   end Write;

   function Read return Pin_State is
      IDR : Unsigned_32 with Address => To_Address (Integer_Address (Port_Base) + IDR_Offset), Volatile;
   begin
      return (if (IDR and Unsigned_32 (Pin_Mask)) /= 0 then High else Low);
   end Read;

   procedure Toggle_Pin is
      ODR : Unsigned_32 with Address => To_Address (Integer_Address (Port_Base) + ODR_Offset), Volatile;
   begin
      ODR := ODR xor Unsigned_32 (Pin_Mask);
   end Toggle_Pin;

end {package_name};
"#, port = port, pin = pin, package_name = package_name);

    DriverOutput {
        header_file: Some(spec),
        source_file: body,
        example_file: Some(format!("--  Usage: {package_name}.Initialize; {package_name}.Toggle_Pin;\n")),
        peripheral_type: PeripheralType::GPIO,
    }
}

/// Generate ARM Assembly GPIO driver
fn generate_gpio_asm(config: &GpioConfig, _arch: &McuArch) -> DriverOutput {
    let port = &config.port;
    let pin = config.pin;
    
    let port_base: u32 = match port.as_str() {
        "A" => 0x4002_0000,
        "B" => 0x4002_0400,
        "C" => 0x4002_0800,
        "D" => 0x4002_0C00,
        "E" => 0x4002_1000,
        _ => 0x4002_0000,
    };
    let pin_mask: u32 = 1 << pin;
    let port_lower = port.to_lowercase();

    let source = format!(r#"@ GPIO Driver for P{port}{pin} - ARM Thumb-2 Assembly
@ Auto-generated by NeuroBench

    .syntax unified
    .cpu cortex-m4
    .thumb

    .equ GPIO{port}_BASE,  0x{port_base:08X}
    .equ GPIO_ODR,         0x14
    .equ GPIO_IDR,         0x10
    .equ GPIO_BSRR,        0x18
    .equ GPIO_MODER,       0x00
    .equ PIN_MASK,         0x{pin_mask:08X}

    .global gpio_{port_lower}{pin}_init
    .global gpio_{port_lower}{pin}_set
    .global gpio_{port_lower}{pin}_clear
    .global gpio_{port_lower}{pin}_toggle
    .global gpio_{port_lower}{pin}_read

gpio_{port_lower}{pin}_init:
    ldr     r1, =GPIO{port}_BASE
    ldr     r0, [r1, #GPIO_MODER]
    bic     r0, r0, #(3 << {pin_shift})
    orr     r0, r0, #(1 << {pin_shift})
    str     r0, [r1, #GPIO_MODER]
    bx      lr

gpio_{port_lower}{pin}_set:
    ldr     r1, =GPIO{port}_BASE
    mov     r0, #PIN_MASK
    str     r0, [r1, #GPIO_BSRR]
    bx      lr

gpio_{port_lower}{pin}_clear:
    ldr     r1, =GPIO{port}_BASE
    mov     r0, #(PIN_MASK << 16)
    str     r0, [r1, #GPIO_BSRR]
    bx      lr

gpio_{port_lower}{pin}_toggle:
    ldr     r1, =GPIO{port}_BASE
    ldr     r0, [r1, #GPIO_ODR]
    eor     r0, r0, #PIN_MASK
    str     r0, [r1, #GPIO_ODR]
    bx      lr

gpio_{port_lower}{pin}_read:
    ldr     r1, =GPIO{port}_BASE
    ldr     r0, [r1, #GPIO_IDR]
    ands    r0, r0, #PIN_MASK
    it      ne
    movne   r0, #1
    bx      lr
    .end
"#, port = port, port_lower = port_lower, pin = pin, 
    port_base = port_base, pin_mask = pin_mask, pin_shift = pin * 2);

    let header = format!(r#"/* GPIO Assembly Driver Header for P{port}{pin} */
#ifndef GPIO_{port}{pin}_ASM_H
#define GPIO_{port}{pin}_ASM_H
extern void gpio_{port_lower}{pin}_init(void);
extern void gpio_{port_lower}{pin}_set(void);
extern void gpio_{port_lower}{pin}_clear(void);
extern void gpio_{port_lower}{pin}_toggle(void);
extern int gpio_{port_lower}{pin}_read(void);
#endif
"#, port = port, port_lower = port_lower, pin = pin);

    DriverOutput {
        header_file: Some(header),
        source_file: source,
        example_file: None,
        peripheral_type: PeripheralType::GPIO,
    }
}

/// Generate MicroPython GPIO driver
fn generate_gpio_micropython(config: &GpioConfig, _arch: &McuArch) -> DriverOutput {
    let port = &config.port;
    let pin = config.pin;
    
    let mode_str = match config.mode {
        GpioMode::Input => "Pin.IN",
        GpioMode::Output => "Pin.OUT",
        GpioMode::AlternateFunction => "Pin.ALT",
        GpioMode::Analog => "Pin.ANALOG",
    };
    
    let pull_str = match config.pull {
        GpioPull::None => "None",
        GpioPull::Up | GpioPull::PullUp => "Pin.PULL_UP",
        GpioPull::Down | GpioPull::PullDown => "Pin.PULL_DOWN",
    };

    let source = format!(r#"""
GPIO Driver for P{port}{pin}
Auto-generated by NeuroBench for MicroPython
"""

from machine import Pin

class GPIO_{port}{pin}:
    """GPIO wrapper for pin P{port}{pin}"""
    
    def __init__(self):
        self.pin = Pin('{port}{pin}', {mode_str}, pull={pull_str})
    
    def write(self, value: bool) -> None:
        """Set pin state"""
        self.pin.value(1 if value else 0)
    
    def read(self) -> bool:
        """Read pin state"""
        return self.pin.value() == 1
    
    def toggle(self) -> None:
        """Toggle pin state"""
        self.pin.value(not self.pin.value())
    
    def on(self) -> None:
        """Set pin high"""
        self.pin.on()
    
    def off(self) -> None:
        """Set pin low"""
        self.pin.off()


# Usage example
if __name__ == "__main__":
    led = GPIO_{port}{pin}()
    import time
    
    while True:
        led.toggle()
        time.sleep_ms(500)
"#, port = port, pin = pin, mode_str = mode_str, pull_str = pull_str);

    DriverOutput {
        header_file: None,
        source_file: source,
        example_file: None,
        peripheral_type: PeripheralType::GPIO,
    }
}

/// Generate Zig GPIO driver
fn generate_gpio_zig(config: &GpioConfig, _arch: &McuArch) -> DriverOutput {
    let port = &config.port;
    let pin = config.pin;
    let _port_lower = port.to_lowercase();

    let source = format!(r#"//! GPIO Driver for P{port}{pin}
//! Auto-generated by NeuroBench for Zig

const std = @import("std");
const gpio = @import("gpio");

pub const Pin_{port}{pin} = struct {{
    const Self = @This();
    
    /// GPIO port
    const port = gpio.Port.{port};
    /// Pin number
    const pin_num = {pin};
    
    /// Initialize the pin
    pub fn init() void {{
        gpio.enable_clock(port);
        gpio.set_mode(port, pin_num, .output);
    }}
    
    /// Write to pin
    pub fn write(state: bool) void {{
        gpio.write_pin(port, pin_num, state);
    }}
    
    /// Read pin state
    pub fn read() bool {{
        return gpio.read_pin(port, pin_num);
    }}
    
    /// Toggle pin
    pub fn toggle() void {{
        const current = read();
        write(!current);
    }}
    
    /// Set pin high
    pub fn set() void {{
        write(true);
    }}
    
    /// Set pin low
    pub fn clear() void {{
        write(false);
    }}
}};

// Usage example
pub fn main() void {{
    Pin_{port}{pin}.init();
    
    while (true) {{
        Pin_{port}{pin}.toggle();
        std.time.sleep(500 * std.time.ns_per_ms);
    }}
}}
"#, port = port, pin = pin);

    DriverOutput {
        header_file: None,
        source_file: source,
        example_file: None,
        peripheral_type: PeripheralType::GPIO,
    }
}


