//! USB Driver Generator
//!
//! Generates USB device/host drivers for CDC, HID, MSC, and custom classes.

use super::templates::*;
use serde::{Deserialize, Serialize};

/// USB configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsbConfig {
    pub mode: UsbMode,
    pub class: UsbClass,
    pub vid: u16,
    pub pid: u16,
    pub manufacturer: String,
    pub product: String,
    pub serial: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum UsbMode {
    Device,
    Host,
    OTG,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum UsbClass {
    CDC,        // Virtual COM port
    HID,        // Human Interface Device
    MSC,        // Mass Storage Class
    Audio,      // Audio class
    MIDI,       // MIDI class
    Custom,     // Custom class
}

impl Default for UsbConfig {
    fn default() -> Self {
        Self {
            mode: UsbMode::Device,
            class: UsbClass::CDC,
            vid: 0x1234,
            pid: 0x5678,
            manufacturer: "NeuroBench".to_string(),
            product: "USB Device".to_string(),
            serial: None,
        }
    }
}

/// Generate USB driver code
pub fn generate_usb_driver(config: &UsbConfig, arch: &McuArch, lang: &DriverLanguage) -> DriverOutput {
    match lang {
        DriverLanguage::C => generate_usb_c(config, arch),
        DriverLanguage::Cpp => generate_usb_cpp(config, arch),
        DriverLanguage::Rust => generate_usb_rust(config, arch),
        DriverLanguage::MicroPython => generate_usb_micropython(config, arch),
        _ => generate_usb_c(config, arch),
    }
}

fn generate_usb_c(config: &UsbConfig, _arch: &McuArch) -> DriverOutput {
    let class_name = match config.class {
        UsbClass::CDC => "CDC",
        UsbClass::HID => "HID",
        UsbClass::MSC => "MSC",
        UsbClass::Audio => "AUDIO",
        UsbClass::MIDI => "MIDI",
        UsbClass::Custom => "CUSTOM",
    };
    
    let vid = config.vid;
    let pid = config.pid;

    let header = format!(r#"/**
 * USB {class_name} Driver
 * Auto-generated by NeuroBench
 * VID: 0x{vid:04X}, PID: 0x{pid:04X}
 */

#ifndef USB_{class_name}_DRIVER_H
#define USB_{class_name}_DRIVER_H

#include <stdint.h>
#include <stdbool.h>

// USB Identifiers
#define USB_VID  0x{vid:04X}
#define USB_PID  0x{pid:04X}

// Function prototypes
void USB_{class_name}_Init(void);
void USB_{class_name}_DeInit(void);
bool USB_{class_name}_IsConnected(void);

#if defined(USB_CLASS_CDC)
int USB_CDC_Transmit(const uint8_t *data, uint16_t len);
int USB_CDC_Receive(uint8_t *data, uint16_t max_len);
int USB_CDC_Available(void);
#endif

#if defined(USB_CLASS_HID)
void USB_HID_SendReport(const uint8_t *report, uint8_t len);
#endif

#if defined(USB_CLASS_MSC)
void USB_MSC_SetCapacity(uint32_t blocks, uint32_t block_size);
#endif

#endif // USB_{class_name}_DRIVER_H
"#);

    let source = format!(r#"/**
 * USB {class_name} Driver Implementation
 * Auto-generated by NeuroBench
 */

#include "usb_{class_name}_driver.h"
#include "usbd_core.h"
#include "usbd_{class_name}.h"

static USBD_HandleTypeDef hUsbDevice;

void USB_{class_name}_Init(void) {{
    // Initialize USB Device Library
    USBD_Init(&hUsbDevice, &{class_name}_Desc, 0);
    USBD_RegisterClass(&hUsbDevice, USBD_{class_name}_CLASS);
    USBD_Start(&hUsbDevice);
}}

void USB_{class_name}_DeInit(void) {{
    USBD_Stop(&hUsbDevice);
    USBD_DeInit(&hUsbDevice);
}}

bool USB_{class_name}_IsConnected(void) {{
    return hUsbDevice.dev_state == USBD_STATE_CONFIGURED;
}}

#if defined(USB_CLASS_CDC)
int USB_CDC_Transmit(const uint8_t *data, uint16_t len) {{
    return CDC_Transmit_FS((uint8_t*)data, len);
}}

int USB_CDC_Receive(uint8_t *data, uint16_t max_len) {{
    // Implementation depends on CDC receive buffer
    return 0;
}}

int USB_CDC_Available(void) {{
    return 0; // Return bytes available
}}
#endif
"#, class_name = class_name.to_lowercase());

    DriverOutput {
        header_file: Some(header),
        source_file: source,
        example_file: None,
        peripheral_type: PeripheralType::USB,
    }
}

fn generate_usb_cpp(config: &UsbConfig, _arch: &McuArch) -> DriverOutput {
    let class_name = match config.class {
        UsbClass::CDC => "Cdc",
        UsbClass::HID => "Hid",
        UsbClass::MSC => "Msc",
        _ => "Device",
    };

    let header = format!(r#"/**
 * USB {class_name} Driver Class
 * Auto-generated by NeuroBench
 */

#pragma once
#include <cstdint>
#include <span>

class Usb{class_name} {{
public:
    static void init();
    static void deinit();
    static bool isConnected();
    
    // CDC methods
    static int transmit(std::span<const uint8_t> data);
    static int receive(std::span<uint8_t> buffer);
    static size_t available();
    
    // HID methods
    static void sendReport(std::span<const uint8_t> report);
}};
"#);

    let source = format!(r#"/**
 * USB {class_name} Driver Implementation
 */

#include "Usb{class_name}.hpp"
#include "usbd_core.h"

static USBD_HandleTypeDef hUsbDevice;

void Usb{class_name}::init() {{
    USBD_Init(&hUsbDevice, nullptr, 0);
    USBD_Start(&hUsbDevice);
}}

void Usb{class_name}::deinit() {{
    USBD_Stop(&hUsbDevice);
    USBD_DeInit(&hUsbDevice);
}}

bool Usb{class_name}::isConnected() {{
    return hUsbDevice.dev_state == USBD_STATE_CONFIGURED;
}}
"#);

    DriverOutput {
        header_file: Some(header),
        source_file: source,
        example_file: None,
        peripheral_type: PeripheralType::USB,
    }
}

fn generate_usb_rust(config: &UsbConfig, _arch: &McuArch) -> DriverOutput {
    let class_name = match config.class {
        UsbClass::CDC => "cdc_acm",
        UsbClass::HID => "hid",
        UsbClass::MSC => "msc",
        _ => "device",
    };
    let vid = config.vid;
    let pid = config.pid;

    let source = format!(r#"//! USB {class_name} Driver
//! Auto-generated by NeuroBench

use usb_device::prelude::*;
use usb_device::class_prelude::*;

pub const USB_VID: u16 = 0x{vid:04X};
pub const USB_PID: u16 = 0x{pid:04X};

/// USB Device wrapper
pub struct UsbDriver<'a, B: UsbBus> {{
    device: UsbDevice<'a, B>,
    class: {class_type}<'a, B>,
}}

impl<'a, B: UsbBus> UsbDriver<'a, B> {{
    pub fn new(alloc: &'a UsbBusAllocator<B>) -> Self {{
        let class = {class_type}::new(alloc);
        
        let device = UsbDeviceBuilder::new(alloc, UsbVidPid(USB_VID, USB_PID))
            .manufacturer("{manufacturer}")
            .product("{product}")
            .device_class(usbd_serial::USB_CLASS_CDC)
            .build();
        
        Self {{ device, class }}
    }}
    
    pub fn poll(&mut self) {{
        self.device.poll(&mut [&mut self.class]);
    }}
    
    pub fn is_connected(&self) -> bool {{
        self.device.state() == UsbDeviceState::Configured
    }}
}}
"#, 
        class_name = class_name,
        vid = vid, pid = pid,
        class_type = match config.class {
            UsbClass::CDC => "SerialPort",
            UsbClass::HID => "HIDClass",
            _ => "UsbClass",
        },
        manufacturer = config.manufacturer,
        product = config.product
    );

    DriverOutput {
        header_file: None,
        source_file: source,
        example_file: None,
        peripheral_type: PeripheralType::USB,
    }
}

fn generate_usb_micropython(config: &UsbConfig, _arch: &McuArch) -> DriverOutput {
    let source = format!(r#"""
USB Driver
Auto-generated by NeuroBench
VID: 0x{vid:04X}, PID: 0x{pid:04X}
"""

import machine
import sys

class UsbCdc:
    """USB CDC (Virtual Serial Port) driver"""
    
    def __init__(self):
        # MicroPython USB is typically handled by sys.stdin/stdout
        self.connected = True
    
    def write(self, data):
        """Write data to USB"""
        if isinstance(data, str):
            data = data.encode()
        sys.stdout.buffer.write(data)
    
    def read(self, nbytes=-1):
        """Read data from USB"""
        return sys.stdin.buffer.read(nbytes)
    
    def readline(self):
        """Read line from USB"""
        return sys.stdin.readline()
    
    def available(self):
        """Check if data available"""
        return sys.stdin.buffer.any()


# Example usage
if __name__ == "__main__":
    usb = UsbCdc()
    usb.write("Hello from USB CDC!\n")
"#, vid = config.vid, pid = config.pid);

    DriverOutput {
        header_file: None,
        source_file: source,
        example_file: None,
        peripheral_type: PeripheralType::USB,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_usb_cdc_c() {
        let config = UsbConfig::default();
        let output = generate_usb_driver(&config, &McuArch::ArmCortexM4, &DriverLanguage::C);
        assert!(output.source_file.contains("CDC"));
    }

    #[test]
    fn test_usb_hid_rust() {
        let config = UsbConfig { class: UsbClass::HID, ..Default::default() };
        let output = generate_usb_driver(&config, &McuArch::ArmCortexM4, &DriverLanguage::Rust);
        assert!(output.source_file.contains("HID"));
    }
}
