//! Hardware Security Module (HSM) Driver
//!
//! Provides secure key storage and cryptographic operations on dedicated hardware.
//! Supports common HSM interfaces like PKCS#11 and vendor-specific APIs.

use serde::{Deserialize, Serialize};

/// HSM configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HsmConfig {
    pub interface: HsmInterface,
    pub slot_id: u8,
    pub pin: Option<String>,
    pub key_storage: KeyStorageType,
}

impl Default for HsmConfig {
    fn default() -> Self {
        Self {
            interface: HsmInterface::Pkcs11,
            slot_id: 0,
            pin: None,
            key_storage: KeyStorageType::NonVolatile,
        }
    }
}

/// HSM interface type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HsmInterface {
    Pkcs11,         // Standard PKCS#11
    NxpSe05x,       // NXP SE050/051
    MicrochipAtEcc, // ATECC608A/B
    Infineon,       // Infineon OPTIGA
    StStsafe,       // ST STSAFE-A110
}

/// Key storage type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum KeyStorageType {
    Volatile,       // Session keys
    NonVolatile,    // Persistent keys
}

/// Key type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HsmKeyType {
    Aes128,
    Aes256,
    EccP256,
    EccP384,
    Rsa2048,
    Rsa4096,
    Ed25519,
    X25519,
}

impl HsmKeyType {
    pub fn key_size_bits(&self) -> u32 {
        match self {
            HsmKeyType::Aes128 => 128,
            HsmKeyType::Aes256 => 256,
            HsmKeyType::EccP256 | HsmKeyType::Ed25519 | HsmKeyType::X25519 => 256,
            HsmKeyType::EccP384 => 384,
            HsmKeyType::Rsa2048 => 2048,
            HsmKeyType::Rsa4096 => 4096,
        }
    }
}

/// Generate HSM driver code
pub fn generate_hsm_driver(config: &HsmConfig) -> HsmOutput {
    let interface_str = format!("{:?}", config.interface);

    let c_code = format!(r#"/**
 * Hardware Security Module Driver
 * Auto-generated by NeuroBench
 * Interface: {interface}
 */

#include <stdint.h>
#include <stdbool.h>

// HSM slot configuration
#define HSM_SLOT_ID {slot_id}

typedef enum {{
    HSM_OK = 0,
    HSM_ERROR_INIT,
    HSM_ERROR_AUTH,
    HSM_ERROR_KEY_NOT_FOUND,
    HSM_ERROR_CRYPTO,
    HSM_ERROR_BUFFER_TOO_SMALL,
}} HsmResult;

typedef enum {{
    KEY_TYPE_AES_128,
    KEY_TYPE_AES_256,
    KEY_TYPE_ECC_P256,
    KEY_TYPE_ECC_P384,
    KEY_TYPE_RSA_2048,
    KEY_TYPE_RSA_4096,
}} HsmKeyType;

typedef struct {{
    uint32_t key_id;
    HsmKeyType type;
    bool exportable;
    bool persistent;
}} HsmKeyHandle;

// Function prototypes
HsmResult HSM_Init(const char *pin);
HsmResult HSM_Deinit(void);
HsmResult HSM_GenerateKey(HsmKeyType type, uint32_t key_id, HsmKeyHandle *handle);
HsmResult HSM_ImportKey(HsmKeyType type, const uint8_t *key, size_t key_len, uint32_t key_id);
HsmResult HSM_DeleteKey(uint32_t key_id);
HsmResult HSM_Sign(uint32_t key_id, const uint8_t *data, size_t data_len, 
                   uint8_t *signature, size_t *sig_len);
HsmResult HSM_Verify(uint32_t key_id, const uint8_t *data, size_t data_len,
                     const uint8_t *signature, size_t sig_len);
HsmResult HSM_Encrypt(uint32_t key_id, const uint8_t *plain, size_t plain_len,
                      uint8_t *cipher, size_t *cipher_len);
HsmResult HSM_Decrypt(uint32_t key_id, const uint8_t *cipher, size_t cipher_len,
                      uint8_t *plain, size_t *plain_len);
HsmResult HSM_DeriveKey(uint32_t base_key_id, const uint8_t *info, size_t info_len,
                        uint32_t derived_key_id);
HsmResult HSM_GetRandom(uint8_t *buffer, size_t len);

/**
 * Initialize HSM
 */
HsmResult HSM_Init(const char *pin) {{
    // Hardware-specific initialization
    // Authenticate with PIN if provided
    return HSM_OK;
}}

/**
 * Generate random bytes
 */
HsmResult HSM_GetRandom(uint8_t *buffer, size_t len) {{
    // Use hardware TRNG
    return HSM_OK;
}}

/**
 * Generate key pair
 */
HsmResult HSM_GenerateKey(HsmKeyType type, uint32_t key_id, HsmKeyHandle *handle) {{
    handle->key_id = key_id;
    handle->type = type;
    handle->exportable = false;
    handle->persistent = true;
    
    // Generate key in HSM
    return HSM_OK;
}}

/**
 * ECDSA Sign
 */
HsmResult HSM_Sign(uint32_t key_id, const uint8_t *data, size_t data_len,
                   uint8_t *signature, size_t *sig_len) {{
    // Hash data first if needed
    // Call HSM sign operation
    return HSM_OK;
}}

/**
 * ECDSA Verify
 */
HsmResult HSM_Verify(uint32_t key_id, const uint8_t *data, size_t data_len,
                     const uint8_t *signature, size_t sig_len) {{
    // Hash data first if needed
    // Call HSM verify operation
    return HSM_OK;
}}
"#, interface = interface_str, slot_id = config.slot_id);

    let rust_code = format!(r#"//! Hardware Security Module Driver
//! Auto-generated by NeuroBench

/// HSM configuration
pub const SLOT_ID: u8 = {slot_id};

/// HSM result type
pub type HsmResult<T> = Result<T, HsmError>;

/// HSM error types
#[derive(Debug, Clone)]
pub enum HsmError {{
    InitFailed,
    AuthFailed,
    KeyNotFound,
    CryptoError,
    BufferTooSmall,
}}

/// Key type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyType {{
    Aes128,
    Aes256,
    EccP256,
    EccP384,
    Rsa2048,
    Ed25519,
}}

/// Key handle
#[derive(Debug, Clone)]
pub struct KeyHandle {{
    pub key_id: u32,
    pub key_type: KeyType,
    pub exportable: bool,
}}

/// HSM driver trait
pub trait HsmDriver {{
    fn init(&mut self, pin: Option<&str>) -> HsmResult<()>;
    fn deinit(&mut self) -> HsmResult<()>;
    fn generate_key(&mut self, key_type: KeyType, key_id: u32) -> HsmResult<KeyHandle>;
    fn delete_key(&mut self, key_id: u32) -> HsmResult<()>;
    fn sign(&self, key_id: u32, data: &[u8]) -> HsmResult<Vec<u8>>;
    fn verify(&self, key_id: u32, data: &[u8], signature: &[u8]) -> HsmResult<bool>;
    fn encrypt(&self, key_id: u32, plaintext: &[u8]) -> HsmResult<Vec<u8>>;
    fn decrypt(&self, key_id: u32, ciphertext: &[u8]) -> HsmResult<Vec<u8>>;
    fn get_random(&self, len: usize) -> HsmResult<Vec<u8>>;
}}

/// ATECC608 driver (example implementation)
pub struct Atecc608<I2C> {{
    i2c: I2C,
    address: u8,
}}

impl<I2C> Atecc608<I2C> {{
    pub fn new(i2c: I2C) -> Self {{
        Self {{ i2c, address: 0x60 }}
    }}
}}
"#, slot_id = config.slot_id);

    HsmOutput { c_code, rust_code }
}

/// HSM driver output
pub struct HsmOutput {
    pub c_code: String,
    pub rust_code: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hsm_key_sizes() {
        assert_eq!(HsmKeyType::Aes256.key_size_bits(), 256);
        assert_eq!(HsmKeyType::EccP256.key_size_bits(), 256);
    }

    #[test]
    fn test_hsm_generation() {
        let config = HsmConfig::default();
        let output = generate_hsm_driver(&config);
        assert!(output.c_code.contains("HSM_Init"));
    }
}
