//! Key Management Driver
//!
//! Provides secure key generation, storage, and lifecycle management.
//! Supports key hierarchies, key wrapping, and secure key export.

use serde::{Deserialize, Serialize};

/// Key management configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyManagementConfig {
    pub storage_backend: KeyStorageBackend,
    pub key_hierarchy: KeyHierarchy,
    pub default_algorithm: KeyAlgorithm,
}

impl Default for KeyManagementConfig {
    fn default() -> Self {
        Self {
            storage_backend: KeyStorageBackend::SecureElement,
            key_hierarchy: KeyHierarchy::default(),
            default_algorithm: KeyAlgorithm::EcdsaP256,
        }
    }
}

/// Key storage backend
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum KeyStorageBackend {
    Flash,          // Encrypted on internal flash
    SecureElement,  // Hardware SE (ATECC, SE050)
    Tpm,            // TPM 2.0
    TrustZone,      // ARM TrustZone
}

/// Key algorithm
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum KeyAlgorithm {
    Aes128Gcm,
    Aes256Gcm,
    ChaCha20Poly1305,
    EcdsaP256,
    EcdsaP384,
    Ed25519,
    X25519,
    Rsa2048,
    Rsa4096,
}

impl KeyAlgorithm {
    pub fn is_symmetric(&self) -> bool {
        matches!(self, 
            KeyAlgorithm::Aes128Gcm | 
            KeyAlgorithm::Aes256Gcm | 
            KeyAlgorithm::ChaCha20Poly1305
        )
    }

    pub fn key_size_bytes(&self) -> usize {
        match self {
            KeyAlgorithm::Aes128Gcm => 16,
            KeyAlgorithm::Aes256Gcm | KeyAlgorithm::ChaCha20Poly1305 => 32,
            KeyAlgorithm::EcdsaP256 | KeyAlgorithm::Ed25519 | KeyAlgorithm::X25519 => 32,
            KeyAlgorithm::EcdsaP384 => 48,
            KeyAlgorithm::Rsa2048 => 256,
            KeyAlgorithm::Rsa4096 => 512,
        }
    }
}

/// Key hierarchy definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyHierarchy {
    pub root_key_type: KeyType,
    pub levels: Vec<KeyLevel>,
}

impl Default for KeyHierarchy {
    fn default() -> Self {
        Self {
            root_key_type: KeyType::DeviceRootKey,
            levels: vec![
                KeyLevel { 
                    key_type: KeyType::ApplicationKey, 
                    derived_from: KeyType::DeviceRootKey 
                },
            ],
        }
    }
}

/// Key level in hierarchy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyLevel {
    pub key_type: KeyType,
    pub derived_from: KeyType,
}

/// Key types in hierarchy
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum KeyType {
    DeviceRootKey,    // DRK - never leaves device
    AttestationKey,   // AIK - for attestation
    EncryptionKey,    // DEK - for data encryption
    SigningKey,       // DSK - for signatures
    ApplicationKey,   // App-specific keys
    SessionKey,       // Ephemeral session keys
}

/// Key metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyMetadata {
    pub id: u32,
    pub key_type: KeyType,
    pub algorithm: KeyAlgorithm,
    pub created_at: u64,
    pub expires_at: Option<u64>,
    pub exportable: bool,
    pub usages: Vec<KeyUsage>,
}

/// Key usage flags
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum KeyUsage {
    Sign,
    Verify,
    Encrypt,
    Decrypt,
    Wrap,
    Unwrap,
    Derive,
}

/// Generate key management driver code
pub fn generate_keys_driver(config: &KeyManagementConfig) -> KeysOutput {
    let backend_str = format!("{:?}", config.storage_backend);

    let c_code = format!(r#"/**
 * Key Management Driver
 * Auto-generated by NeuroBench
 * Backend: {backend}
 */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

// Key types
#define KEY_TYPE_ROOT       0x01
#define KEY_TYPE_ATTEST     0x02
#define KEY_TYPE_ENCRYPT    0x03
#define KEY_TYPE_SIGN       0x04
#define KEY_TYPE_APP        0x05
#define KEY_TYPE_SESSION    0x06

// Key algorithms
#define KEY_ALG_AES128_GCM      0x10
#define KEY_ALG_AES256_GCM      0x11
#define KEY_ALG_CHACHA20_POLY   0x12
#define KEY_ALG_ECDSA_P256      0x20
#define KEY_ALG_ECDSA_P384      0x21
#define KEY_ALG_ED25519         0x22

// Key usage flags
#define KEY_USAGE_SIGN      0x01
#define KEY_USAGE_VERIFY    0x02
#define KEY_USAGE_ENCRYPT   0x04
#define KEY_USAGE_DECRYPT   0x08
#define KEY_USAGE_WRAP      0x10
#define KEY_USAGE_UNWRAP    0x20
#define KEY_USAGE_DERIVE    0x40

typedef enum {{
    KEYS_OK = 0,
    KEYS_ERROR_INIT,
    KEYS_ERROR_NOT_FOUND,
    KEYS_ERROR_PERMISSION,
    KEYS_ERROR_STORAGE,
    KEYS_ERROR_CRYPTO,
}} KeysResult;

typedef struct {{
    uint32_t id;
    uint8_t key_type;
    uint8_t algorithm;
    uint8_t usages;
    bool exportable;
    uint64_t created;
    uint64_t expires;
}} KeyMetadata;

typedef struct {{
    uint32_t id;
    uint8_t type;
    void *handle;  // Opaque handle to actual key
}} KeyHandle;

// Function prototypes
KeysResult Keys_Init(void);
KeysResult Keys_Generate(uint8_t key_type, uint8_t algorithm, uint8_t usages, KeyHandle *handle);
KeysResult Keys_Import(const uint8_t *key_data, size_t len, KeyMetadata *metadata, KeyHandle *handle);
KeysResult Keys_Export(KeyHandle *handle, const KeyHandle *wrapping_key, uint8_t *wrapped, size_t *len);
KeysResult Keys_Delete(uint32_t key_id);
KeysResult Keys_Derive(KeyHandle *base, const uint8_t *info, size_t info_len, KeyHandle *derived);
KeysResult Keys_GetMetadata(uint32_t key_id, KeyMetadata *metadata);
KeysResult Keys_Wrap(KeyHandle *kek, const uint8_t *key, size_t key_len, uint8_t *wrapped, size_t *wrapped_len);
KeysResult Keys_Unwrap(KeyHandle *kek, const uint8_t *wrapped, size_t wrapped_len, KeyHandle *unwrapped);
KeysResult Keys_RotateRoot(void);

/**
 * Initialize key management subsystem
 */
KeysResult Keys_Init(void) {{
    // Initialize storage backend
    // Load root key or derive from hardware unique ID
    return KEYS_OK;
}}

/**
 * Generate new key
 */
KeysResult Keys_Generate(uint8_t key_type, uint8_t algorithm, uint8_t usages, KeyHandle *handle) {{
    // Generate key material
    // Store in secure storage
    // Return handle
    return KEYS_OK;
}}

/**
 * Derive key from base key
 */
KeysResult Keys_Derive(KeyHandle *base, const uint8_t *info, size_t info_len, KeyHandle *derived) {{
    // HKDF-Expand with info
    // Store derived key
    return KEYS_OK;
}}

/**
 * Key wrapping (RFC 3394 / AES-KW)
 */
KeysResult Keys_Wrap(KeyHandle *kek, const uint8_t *key, size_t key_len,
                     uint8_t *wrapped, size_t *wrapped_len) {{
    // AES Key Wrap with integrity check
    return KEYS_OK;
}}

/**
 * Export key (wrapped)
 */
KeysResult Keys_Export(KeyHandle *handle, const KeyHandle *wrapping_key,
                       uint8_t *wrapped, size_t *len) {{
    // Check export permission
    // Wrap with KEK
    // Return wrapped key
    return KEYS_OK;
}}

/**
 * Rotate root key (for key compromise recovery)
 */
KeysResult Keys_RotateRoot(void) {{
    // Generate new root
    // Re-wrap all dependent keys
    // Securely erase old root
    return KEYS_OK;
}}
"#, backend = backend_str);

    let rust_code = format!(r#"//! Key Management Driver
//! Auto-generated by NeuroBench

use core::fmt;

/// Key management result type
pub type KeysResult<T> = Result<T, KeysError>;

/// Key management errors
#[derive(Debug, Clone)]
pub enum KeysError {{
    InitFailed,
    NotFound,
    PermissionDenied,
    StorageFull,
    CryptoError,
    InvalidKey,
}}

/// Key algorithm
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyAlgorithm {{
    Aes128Gcm,
    Aes256Gcm,
    ChaCha20Poly1305,
    EcdsaP256,
    EcdsaP384,
    Ed25519,
    X25519,
}}

/// Key type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyType {{
    Root,
    Attestation,
    Encryption,
    Signing,
    Application,
    Session,
}}

/// Key usage flags
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct KeyUsage(u8);

impl KeyUsage {{
    pub const SIGN: KeyUsage = KeyUsage(0x01);
    pub const VERIFY: KeyUsage = KeyUsage(0x02);
    pub const ENCRYPT: KeyUsage = KeyUsage(0x04);
    pub const DECRYPT: KeyUsage = KeyUsage(0x08);
    pub const WRAP: KeyUsage = KeyUsage(0x10);
    pub const UNWRAP: KeyUsage = KeyUsage(0x20);
    pub const DERIVE: KeyUsage = KeyUsage(0x40);
    
    pub fn contains(&self, other: KeyUsage) -> bool {{
        (self.0 & other.0) != 0
    }}
}}

/// Key metadata
#[derive(Debug, Clone)]
pub struct KeyMetadata {{
    pub id: u32,
    pub key_type: KeyType,
    pub algorithm: KeyAlgorithm,
    pub usages: KeyUsage,
    pub exportable: bool,
    pub created_at: u64,
    pub expires_at: Option<u64>,
}}

/// Key handle (opaque)
#[derive(Clone)]
pub struct KeyHandle {{
    id: u32,
    key_type: KeyType,
}}

impl fmt::Debug for KeyHandle {{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{
        f.debug_struct("KeyHandle")
            .field("id", &self.id)
            .field("type", &self.key_type)
            .finish()
    }}
}}

/// Key management trait
pub trait KeyManager {{
    fn init(&mut self) -> KeysResult<()>;
    fn generate(&mut self, key_type: KeyType, algorithm: KeyAlgorithm, usages: KeyUsage) 
        -> KeysResult<KeyHandle>;
    fn import(&mut self, key_data: &[u8], metadata: KeyMetadata) -> KeysResult<KeyHandle>;
    fn export(&self, handle: &KeyHandle, wrapping_key: &KeyHandle) -> KeysResult<Vec<u8>>;
    fn delete(&mut self, id: u32) -> KeysResult<()>;
    fn derive(&mut self, base: &KeyHandle, info: &[u8]) -> KeysResult<KeyHandle>;
    fn get_metadata(&self, id: u32) -> KeysResult<KeyMetadata>;
    fn wrap(&self, kek: &KeyHandle, key_data: &[u8]) -> KeysResult<Vec<u8>>;
    fn unwrap(&self, kek: &KeyHandle, wrapped: &[u8]) -> KeysResult<KeyHandle>;
}}
"#);

    KeysOutput { c_code, rust_code }
}

/// Keys driver output
pub struct KeysOutput {
    pub c_code: String,
    pub rust_code: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_key_algorithm_symmetric() {
        assert!(KeyAlgorithm::Aes256Gcm.is_symmetric());
        assert!(!KeyAlgorithm::EcdsaP256.is_symmetric());
    }

    #[test]
    fn test_keys_generation() {
        let config = KeyManagementConfig::default();
        let output = generate_keys_driver(&config);
        assert!(output.c_code.contains("Keys_Init"));
    }
}
