//! TPM (Trusted Platform Module) Driver
//!
//! Provides TPM 2.0 interface for secure boot, attestation, and key management.
//! Supports discrete TPMs and firmware-based fTPMs.

use serde::{Deserialize, Serialize};

/// TPM configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TpmConfig {
    pub interface: TpmInterface,
    pub hierarchy: TpmHierarchy,
    pub pcr_banks: Vec<u8>,
}

impl Default for TpmConfig {
    fn default() -> Self {
        Self {
            interface: TpmInterface::Spi,
            hierarchy: TpmHierarchy::Owner,
            pcr_banks: vec![0, 1, 2, 3, 4, 5, 6, 7],
        }
    }
}

/// TPM interface type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TpmInterface {
    Spi,
    I2c,
    Lpc,
    Firmware, // fTPM
}

/// TPM hierarchy
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TpmHierarchy {
    Platform,
    Owner,
    Endorsement,
    Null,
}

/// PCR (Platform Configuration Register) value
#[derive(Debug, Clone)]
pub struct PcrValue {
    pub index: u8,
    pub digest: [u8; 32],
    pub algorithm: HashAlgorithm,
}

/// Hash algorithm
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HashAlgorithm {
    Sha1,
    Sha256,
    Sha384,
    Sha512,
}

impl HashAlgorithm {
    pub fn digest_size(&self) -> usize {
        match self {
            HashAlgorithm::Sha1 => 20,
            HashAlgorithm::Sha256 => 32,
            HashAlgorithm::Sha384 => 48,
            HashAlgorithm::Sha512 => 64,
        }
    }
}

/// Generate TPM driver code
pub fn generate_tpm_driver(config: &TpmConfig) -> TpmOutput {
    let interface_str = format!("{:?}", config.interface);

    let c_code = format!(r#"/**
 * TPM 2.0 Driver
 * Auto-generated by NeuroBench
 * Interface: {interface}
 */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

// TPM2 command codes
#define TPM2_CC_Startup         0x00000144
#define TPM2_CC_Shutdown        0x00000145
#define TPM2_CC_SelfTest        0x00000143
#define TPM2_CC_PCR_Extend      0x00000182
#define TPM2_CC_PCR_Read        0x0000017E
#define TPM2_CC_CreatePrimary   0x00000131
#define TPM2_CC_Create          0x00000153
#define TPM2_CC_Sign            0x0000015D
#define TPM2_CC_VerifySignature 0x00000177
#define TPM2_CC_Quote           0x00000158
#define TPM2_CC_GetRandom       0x0000017B

// Algorithm IDs
#define TPM2_ALG_SHA256         0x000B
#define TPM2_ALG_RSA            0x0001
#define TPM2_ALG_ECC            0x0023
#define TPM2_ALG_ECDSA          0x0018

typedef enum {{
    TPM_OK = 0,
    TPM_ERROR_INIT,
    TPM_ERROR_COMM,
    TPM_ERROR_AUTH,
    TPM_ERROR_PCR,
    TPM_ERROR_KEY,
}} TpmResult;

typedef struct {{
    uint8_t digest[32];
    uint8_t algorithm;
}} TpmPcr;

typedef struct {{
    uint32_t handle;
    uint16_t algorithm;
    bool persistent;
}} TpmKeyHandle;

// Function prototypes
TpmResult TPM_Init(void);
TpmResult TPM_Startup(void);
TpmResult TPM_Shutdown(void);
TpmResult TPM_SelfTest(bool full);
TpmResult TPM_PcrExtend(uint8_t pcr_index, const uint8_t *digest, size_t len);
TpmResult TPM_PcrRead(uint8_t pcr_index, TpmPcr *pcr);
TpmResult TPM_CreatePrimaryKey(uint32_t *handle);
TpmResult TPM_Sign(uint32_t key_handle, const uint8_t *digest, size_t len,
                   uint8_t *signature, size_t *sig_len);
TpmResult TPM_Quote(uint8_t *pcr_selection, size_t pcr_count,
                    uint8_t *quote, size_t *quote_len);
TpmResult TPM_GetRandom(uint8_t *buffer, size_t len);
TpmResult TPM_Seal(uint32_t key_handle, const uint8_t *data, size_t len,
                   uint8_t *pcr_policy, size_t pcr_count,
                   uint8_t *sealed, size_t *sealed_len);
TpmResult TPM_Unseal(uint32_t key_handle, const uint8_t *sealed, size_t sealed_len,
                     uint8_t *data, size_t *data_len);

/**
 * Initialize TPM
 */
TpmResult TPM_Init(void) {{
    // Initialize SPI/I2C interface
    // Perform locality request
    // Check TPM version
    return TPM_OK;
}}

/**
 * TPM Startup (call after power-on)
 */
TpmResult TPM_Startup(void) {{
    // Send TPM2_Startup command
    return TPM_OK;
}}

/**
 * Extend PCR with measurement
 */
TpmResult TPM_PcrExtend(uint8_t pcr_index, const uint8_t *digest, size_t len) {{
    // Build TPM2_PCR_Extend command
    // Send via SPI/I2C
    return TPM_OK;
}}

/**
 * Read PCR value
 */
TpmResult TPM_PcrRead(uint8_t pcr_index, TpmPcr *pcr) {{
    // Build TPM2_PCR_Read command
    // Parse response
    return TPM_OK;
}}

/**
 * Generate attestation quote
 */
TpmResult TPM_Quote(uint8_t *pcr_selection, size_t pcr_count,
                    uint8_t *quote, size_t *quote_len) {{
    // Build TPM2_Quote command with PCR selection
    // Sign with attestation key
    return TPM_OK;
}}

/**
 * Seal data to PCR state
 */
TpmResult TPM_Seal(uint32_t key_handle, const uint8_t *data, size_t len,
                   uint8_t *pcr_policy, size_t pcr_count,
                   uint8_t *sealed, size_t *sealed_len) {{
    // Create sealed object with PCR policy
    return TPM_OK;
}}
"#, interface = interface_str);

    let rust_code = format!(r#"//! TPM 2.0 Driver
//! Auto-generated by NeuroBench

/// TPM result type
pub type TpmResult<T> = Result<T, TpmError>;

/// TPM error types
#[derive(Debug, Clone)]
pub enum TpmError {{
    InitFailed,
    CommError,
    AuthFailed,
    PcrError,
    KeyError,
    Unsupported,
}}

/// Hash algorithm
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HashAlg {{
    Sha1,
    Sha256,
    Sha384,
}}

/// PCR value
#[derive(Debug, Clone)]
pub struct PcrValue {{
    pub index: u8,
    pub digest: Vec<u8>,
    pub algorithm: HashAlg,
}}

/// TPM key handle
#[derive(Debug, Clone)]
pub struct TpmKey {{
    pub handle: u32,
    pub persistent: bool,
}}

/// TPM driver trait
pub trait TpmDriver {{
    fn init(&mut self) -> TpmResult<()>;
    fn startup(&mut self) -> TpmResult<()>;
    fn shutdown(&mut self) -> TpmResult<()>;
    fn self_test(&mut self, full: bool) -> TpmResult<()>;
    fn pcr_extend(&mut self, index: u8, digest: &[u8]) -> TpmResult<()>;
    fn pcr_read(&self, index: u8) -> TpmResult<PcrValue>;
    fn create_primary(&mut self) -> TpmResult<TpmKey>;
    fn sign(&self, key: &TpmKey, digest: &[u8]) -> TpmResult<Vec<u8>>;
    fn quote(&self, pcrs: &[u8], nonce: &[u8]) -> TpmResult<Vec<u8>>;
    fn seal(&self, key: &TpmKey, data: &[u8], pcrs: &[u8]) -> TpmResult<Vec<u8>>;
    fn unseal(&self, key: &TpmKey, sealed: &[u8]) -> TpmResult<Vec<u8>>;
    fn get_random(&self, len: usize) -> TpmResult<Vec<u8>>;
}}

/// Attestation quote structure
#[derive(Debug, Clone)]
pub struct Quote {{
    pub pcr_digest: Vec<u8>,
    pub nonce: Vec<u8>,
    pub signature: Vec<u8>,
}}
"#);

    TpmOutput { c_code, rust_code }
}

/// TPM driver output
pub struct TpmOutput {
    pub c_code: String,
    pub rust_code: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tpm_default() {
        let config = TpmConfig::default();
        assert_eq!(config.hierarchy, TpmHierarchy::Owner);
    }

    #[test]
    fn test_hash_digest_size() {
        assert_eq!(HashAlgorithm::Sha256.digest_size(), 32);
    }
}
