//! Matter Protocol Stack Generator
//!
//! Generates Matter (formerly CHIP) smart home protocol code.
//! Works over Thread, WiFi, and Ethernet.

use serde::{Deserialize, Serialize};

/// Matter device configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MatterConfig {
    pub device_type: MatterDeviceType,
    pub vendor_id: u16,
    pub product_id: u16,
    pub device_name: String,
    pub transport: MatterTransport,
    pub commissioning: CommissioningConfig,
}

impl Default for MatterConfig {
    fn default() -> Self {
        Self {
            device_type: MatterDeviceType::OnOffLight,
            vendor_id: 0xFFF1,
            product_id: 0x8000,
            device_name: "Matter Device".to_string(),
            transport: MatterTransport::Thread,
            commissioning: CommissioningConfig::default(),
        }
    }
}

/// Matter device types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MatterDeviceType {
    OnOffLight,
    DimmableLight,
    ColorLight,
    OnOffSwitch,
    DimmerSwitch,
    DoorLock,
    Thermostat,
    TemperatureSensor,
    OccupancySensor,
    ContactSensor,
    WindowCovering,
    Fan,
}

impl MatterDeviceType {
    pub fn cluster_id(&self) -> u16 {
        match self {
            MatterDeviceType::OnOffLight | MatterDeviceType::OnOffSwitch => 0x0006,
            MatterDeviceType::DimmableLight | MatterDeviceType::DimmerSwitch => 0x0008,
            MatterDeviceType::ColorLight => 0x0300,
            MatterDeviceType::DoorLock => 0x0101,
            MatterDeviceType::Thermostat => 0x0201,
            MatterDeviceType::TemperatureSensor => 0x0402,
            MatterDeviceType::OccupancySensor => 0x0406,
            MatterDeviceType::ContactSensor => 0x0045,
            MatterDeviceType::WindowCovering => 0x0102,
            MatterDeviceType::Fan => 0x0202,
        }
    }
}

/// Matter transport layer
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MatterTransport {
    Thread,
    WiFi,
    Ethernet,
    BridgedDevice,
}

/// Commissioning configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommissioningConfig {
    pub discriminator: u16,
    pub setup_pin: u32,
    pub qr_code_enabled: bool,
}

impl Default for CommissioningConfig {
    fn default() -> Self {
        Self {
            discriminator: 3840,
            setup_pin: 20202021,
            qr_code_enabled: true,
        }
    }
}

/// Generate Matter driver code
pub fn generate_matter_driver(config: &MatterConfig) -> MatterOutput {
    let device_type_str = format!("{:?}", config.device_type);

    let c_code = format!(r#"/**
 * Matter Device Driver
 * Auto-generated by NeuroBench
 * Device: {device_name} ({device_type})
 */

#include <app/server/Server.h>
#include <app/clusters/on-off-server/on-off-server.h>
#include <platform/CHIPDeviceLayer.h>

// Device configuration
#define MATTER_VENDOR_ID    0x{vendor_id:04X}
#define MATTER_PRODUCT_ID   0x{product_id:04X}
#define MATTER_DISCRIMINATOR {discriminator}
#define MATTER_SETUP_PIN    {setup_pin}

using namespace chip;
using namespace chip::app;

/**
 * Initialize Matter stack
 */
void Matter_Init(void) {{
    // Initialize platform
    DeviceLayer::PlatformMgr().InitChipStack();
    
    // Set device info
    DeviceLayer::ConfigurationMgr().StoreVendorId(MATTER_VENDOR_ID);
    DeviceLayer::ConfigurationMgr().StoreProductId(MATTER_PRODUCT_ID);
    
    // Start Matter server
    static chip::Server::InitParams initParams;
    chip::Server::GetInstance().Init(initParams);
    
    // Start commissioning
    DeviceLayer::PlatformMgr().StartEventLoopTask();
}}

/**
 * Handle attribute change
 */
void Matter_OnAttributeChange(EndpointId endpoint, ClusterId cluster, AttributeId attribute) {{
    // Handle attribute updates
}}

/**
 * Set On/Off state (for light/switch devices)
 */
void Matter_SetOnOff(bool state) {{
    Clusters::OnOff::Attributes::OnOff::Set(1, state);
}}

/**
 * Get On/Off state
 */
bool Matter_GetOnOff(void) {{
    bool state = false;
    Clusters::OnOff::Attributes::OnOff::Get(1, &state);
    return state;
}}
"#, 
        device_name = config.device_name,
        device_type = device_type_str,
        vendor_id = config.vendor_id,
        product_id = config.product_id,
        discriminator = config.commissioning.discriminator,
        setup_pin = config.commissioning.setup_pin
    );

    let rust_code = format!(r#"//! Matter Device Driver
//! Auto-generated by NeuroBench

/// Device configuration
pub const VENDOR_ID: u16 = 0x{vendor_id:04X};
pub const PRODUCT_ID: u16 = 0x{product_id:04X};
pub const DISCRIMINATOR: u16 = {discriminator};

/// Matter device trait
pub trait MatterDevice {{
    fn get_device_type(&self) -> u16;
    fn get_endpoint(&self) -> u8;
    fn handle_command(&mut self, cluster: u16, command: u8, data: &[u8]);
    fn report_attribute(&self, cluster: u16, attribute: u16) -> Vec<u8>;
}}

/// On/Off Light device
pub struct OnOffLight {{
    endpoint: u8,
    on: bool,
}}

impl OnOffLight {{
    pub fn new(endpoint: u8) -> Self {{
        Self {{ endpoint, on: false }}
    }}
    
    pub fn set_on(&mut self, state: bool) {{
        self.on = state;
    }}
    
    pub fn is_on(&self) -> bool {{
        self.on
    }}
}}

impl MatterDevice for OnOffLight {{
    fn get_device_type(&self) -> u16 {{ 0x0100 }} // On/Off Light
    fn get_endpoint(&self) -> u8 {{ self.endpoint }}
    
    fn handle_command(&mut self, cluster: u16, command: u8, _data: &[u8]) {{
        if cluster == 0x0006 {{ // On/Off cluster
            match command {{
                0x00 => self.on = false, // Off
                0x01 => self.on = true,  // On
                0x02 => self.on = !self.on, // Toggle
                _ => {{}}
            }}
        }}
    }}
    
    fn report_attribute(&self, cluster: u16, attribute: u16) -> Vec<u8> {{
        if cluster == 0x0006 && attribute == 0x0000 {{
            vec![self.on as u8]
        }} else {{
            vec![]
        }}
    }}
}}
"#, 
        vendor_id = config.vendor_id,
        product_id = config.product_id,
        discriminator = config.commissioning.discriminator
    );

    MatterOutput { c_code, rust_code }
}

/// Matter driver output
pub struct MatterOutput {
    pub c_code: String,
    pub rust_code: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_matter_default() {
        let config = MatterConfig::default();
        assert_eq!(config.device_type, MatterDeviceType::OnOffLight);
    }

    #[test]
    fn test_matter_generation() {
        let config = MatterConfig::default();
        let output = generate_matter_driver(&config);
        assert!(output.c_code.contains("Matter_Init"));
    }
}
