//! Node Code Generation
//!
//! Generates embedded C/C++ code from node configurations

use super::node_types::*;
use std::collections::HashMap;

/// Code generation context
pub struct CodeGenContext {
    pub target: CodeTarget,
    pub language: CodeLanguage,
    pub hal_framework: HalFramework,
    pub include_comments: bool,
}

impl Default for CodeGenContext {
    fn default() -> Self {
        Self {
            target: CodeTarget::Stm32,
            language: CodeLanguage::C,
            hal_framework: HalFramework::Hal,
            include_comments: true,
        }
    }
}

/// Target MCU family
#[derive(Debug, Clone, Copy)]
pub enum CodeTarget {
    Stm32,
    Esp32,
    Avr,
    Rp2040,
    Generic,
}

/// Output language
#[derive(Debug, Clone, Copy)]
pub enum CodeLanguage {
    C,
    Cpp,
    Rust,
}

/// HAL framework to use
#[derive(Debug, Clone, Copy)]
pub enum HalFramework {
    Hal,      // STM32 HAL
    Ll,       // STM32 LL
    Register, // Direct register
    Arduino,  // Arduino framework
}

/// Generated code with structure
#[derive(Debug, Clone, serde::Serialize)]
pub struct GeneratedCode {
    pub includes: Vec<String>,
    pub defines: Vec<String>,
    pub types: Vec<String>,
    pub globals: Vec<String>,
    pub init_code: Vec<String>,
    pub handler_code: Vec<String>,
    pub main_loop: Vec<String>,
}

impl GeneratedCode {
    pub fn new() -> Self {
        Self {
            includes: Vec::new(),
            defines: Vec::new(),
            types: Vec::new(),
            globals: Vec::new(),
            init_code: Vec::new(),
            handler_code: Vec::new(),
            main_loop: Vec::new(),
        }
    }
    
    /// Merge another generated code into this one
    pub fn merge(&mut self, other: GeneratedCode) {
        self.includes.extend(other.includes);
        self.defines.extend(other.defines);
        self.types.extend(other.types);
        self.globals.extend(other.globals);
        self.init_code.extend(other.init_code);
        self.handler_code.extend(other.handler_code);
        self.main_loop.extend(other.main_loop);
    }
    
    /// Render to complete source file
    pub fn render(&self) -> String {
        let mut output = String::new();
        
        // Includes
        let mut includes: Vec<_> = self.includes.iter().collect();
        includes.sort();
        includes.dedup();
        for inc in includes {
            output.push_str(&format!("#include {}\n", inc));
        }
        output.push('\n');
        
        // Defines
        for def in &self.defines {
            output.push_str(&format!("#define {}\n", def));
        }
        if !self.defines.is_empty() {
            output.push('\n');
        }
        
        // Types
        for typ in &self.types {
            output.push_str(typ);
            output.push_str("\n\n");
        }
        
        // Globals
        for global in &self.globals {
            output.push_str(global);
            output.push('\n');
        }
        if !self.globals.is_empty() {
            output.push('\n');
        }
        
        // Handler functions
        for handler in &self.handler_code {
            output.push_str(handler);
            output.push_str("\n\n");
        }
        
        // Init function
        output.push_str("void System_Init(void) {\n");
        for init in &self.init_code {
            output.push_str("    ");
            output.push_str(init);
            output.push('\n');
        }
        output.push_str("}\n\n");
        
        // Main loop
        output.push_str("void System_Update(void) {\n");
        for main in &self.main_loop {
            output.push_str("    ");
            output.push_str(main);
            output.push('\n');
        }
        output.push_str("}\n");
        
        output
    }
    
    /// Render to multiple files for project structure
    pub fn render_multi_file(&self) -> Vec<CodeFile> {
        let mut files = Vec::new();
        
        // 1. hal_config.h - Hardware configuration header
        let mut hal_h = String::new();
        hal_h.push_str("/**\n * hal_config.h\n * Generated by NeuroBench\n */\n\n");
        hal_h.push_str("#ifndef HAL_CONFIG_H\n#define HAL_CONFIG_H\n\n");
        
        // Includes
        let mut includes: Vec<_> = self.includes.iter().collect();
        includes.sort();
        includes.dedup();
        for inc in includes {
            hal_h.push_str(&format!("#include {}\n", inc));
        }
        hal_h.push('\n');
        
        // Defines
        for def in &self.defines {
            hal_h.push_str(&format!("#define {}\n", def));
        }
        hal_h.push('\n');
        
        // Types
        for typ in &self.types {
            hal_h.push_str(typ);
            hal_h.push_str("\n\n");
        }
        
        // Extern declarations for globals
        for global in &self.globals {
            if global.contains("=") {
                let decl = global.split('=').next().unwrap_or(global);
                hal_h.push_str(&format!("extern {};\n", decl.trim()));
            } else {
                hal_h.push_str(&format!("extern {};\n", global.trim_end_matches(';')));
            }
        }
        hal_h.push('\n');
        
        // Function prototypes
        hal_h.push_str("// System functions\n");
        hal_h.push_str("void System_Init(void);\n");
        hal_h.push_str("void System_Update(void);\n\n");
        
        hal_h.push_str("#endif // HAL_CONFIG_H\n");
        
        files.push(CodeFile {
            name: "hal_config.h".to_string(),
            content: hal_h,
            language: "c".to_string(),
        });
        
        // 2. hal_config.c - Hardware implementation
        let mut hal_c = String::new();
        hal_c.push_str("/**\n * hal_config.c\n * Generated by NeuroBench\n */\n\n");
        hal_c.push_str("#include \"hal_config.h\"\n\n");
        
        // Global variables
        for global in &self.globals {
            hal_c.push_str(global);
            hal_c.push('\n');
        }
        hal_c.push('\n');
        
        // Init function
        hal_c.push_str("void System_Init(void) {\n");
        for init in &self.init_code {
            hal_c.push_str("    ");
            hal_c.push_str(init);
            hal_c.push('\n');
        }
        hal_c.push_str("}\n\n");
        
        // Update function
        hal_c.push_str("void System_Update(void) {\n");
        for main in &self.main_loop {
            hal_c.push_str("    ");
            hal_c.push_str(main);
            hal_c.push('\n');
        }
        hal_c.push_str("}\n");
        
        files.push(CodeFile {
            name: "hal_config.c".to_string(),
            content: hal_c,
            language: "c".to_string(),
        });
        
        // 3. handlers.c - Interrupt and callback handlers
        if !self.handler_code.is_empty() {
            let mut handlers_c = String::new();
            handlers_c.push_str("/**\n * handlers.c\n * Interrupt and callback handlers\n * Generated by NeuroBench\n */\n\n");
            handlers_c.push_str("#include \"hal_config.h\"\n\n");
            
            for handler in &self.handler_code {
                handlers_c.push_str(handler);
                handlers_c.push_str("\n\n");
            }
            
            files.push(CodeFile {
                name: "handlers.c".to_string(),
                content: handlers_c,
                language: "c".to_string(),
            });
        }
        
        // 4. main.c - Application entry point
        let mut main_c = String::new();
        main_c.push_str("/**\n * main.c\n * Application entry point\n * Generated by NeuroBench\n */\n\n");
        main_c.push_str("#include \"hal_config.h\"\n\n");
        main_c.push_str("int main(void) {\n");
        main_c.push_str("    // Initialize HAL\n");
        main_c.push_str("    HAL_Init();\n\n");
        main_c.push_str("    // Initialize peripherals\n");
        main_c.push_str("    System_Init();\n\n");
        main_c.push_str("    // Main loop\n");
        main_c.push_str("    while (1) {\n");
        main_c.push_str("        System_Update();\n");
        main_c.push_str("    }\n");
        main_c.push_str("}\n");
        
        files.push(CodeFile {
            name: "main.c".to_string(),
            content: main_c,
            language: "c".to_string(),
        });
        
        files
    }
}

/// A single code file for multi-file export
#[derive(Debug, Clone, serde::Serialize)]
pub struct CodeFile {
    pub name: String,
    pub content: String,
    pub language: String,
}

impl Default for GeneratedCode {
    fn default() -> Self {
        Self::new()
    }
}

/// Generate code for a specific node type with properties
pub fn generate_node_code(
    node_type: &NodeType,
    properties: &HashMap<String, PropertyValue>,
    ctx: &CodeGenContext,
) -> GeneratedCode {
    match node_type {
        // ===== Hardware Nodes =====
        NodeType::Gpio => generate_gpio_code(properties, ctx),
        NodeType::Adc => generate_adc_code(properties, ctx),
        NodeType::Dac => generate_dac_code(properties, ctx),
        NodeType::Pwm => generate_pwm_code(properties, ctx),
        NodeType::Uart => generate_uart_code(properties, ctx),
        NodeType::Spi => generate_spi_code(properties, ctx),
        NodeType::I2c => generate_i2c_code(properties, ctx),
        NodeType::Timer => generate_timer_code(properties, ctx),
        
        // ===== Control/RTOS Nodes =====
        NodeType::Task => generate_task_code(properties, ctx),
        NodeType::Semaphore => generate_semaphore_code(properties, ctx),
        NodeType::Mutex => generate_mutex_code(properties, ctx),
        NodeType::Queue => generate_queue_code(properties, ctx),
        NodeType::Interrupt => generate_interrupt_code(properties, ctx),
        
        // ===== I/O Nodes =====
        NodeType::Led => generate_led_code(properties, ctx),
        NodeType::Button => generate_button_code(properties, ctx),
        NodeType::Motor => generate_motor_code(properties, ctx),
        
        // ===== FSM Nodes =====
        NodeType::State | NodeType::Initial | NodeType::Final => 
            generate_state_code(node_type, properties, ctx),
        
        // Default - empty code
        _ => GeneratedCode::new(),
    }
}

// ============================================================================
// Hardware Node Code Generators
// ============================================================================

fn generate_gpio_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    // Extract properties
    let port = prop_str(props, "port", "A");
    let pin = prop_int(props, "pin", 0);
    let mode = prop_enum(props, "mode", "Output");
    let pull = prop_enum(props, "pull", "NoPull");
    
    code.includes.push("<stm32f4xx_hal.h>".to_string());
    
    let pin_name = format!("GPIO_PIN_{}", pin);
    let port_name = format!("GPIO{}", port);
    
    // Define
    code.defines.push(format!("USER_GPIO_PORT {}", port_name));
    code.defines.push(format!("USER_GPIO_PIN {}", pin_name));
    
    // Init code
    let mode_value = match mode.as_str() {
        "Input" => "GPIO_MODE_INPUT",
        "Output" => "GPIO_MODE_OUTPUT_PP",
        "Alternate" => "GPIO_MODE_AF_PP",
        "Analog" => "GPIO_MODE_ANALOG",
        _ => "GPIO_MODE_OUTPUT_PP",
    };
    
    let pull_value = match pull.as_str() {
        "Up" => "GPIO_PULLUP",
        "Down" => "GPIO_PULLDOWN",
        _ => "GPIO_NOPULL",
    };
    
    code.init_code.push(format!(
        "__HAL_{}_CLK_ENABLE();",
        port_name
    ));
    
    code.init_code.push(format!(
        "GPIO_InitTypeDef gpio_init = {{ .Pin = {}, .Mode = {}, .Pull = {}, .Speed = GPIO_SPEED_FREQ_HIGH }};",
        pin_name, mode_value, pull_value
    ));
    
    code.init_code.push(format!(
        "HAL_GPIO_Init({}, &gpio_init);",
        port_name
    ));
    
    code
}

fn generate_adc_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let channel = prop_int(props, "channel", 0);
    let resolution = prop_int(props, "resolution", 12);
    
    code.includes.push("<stm32f4xx_hal.h>".to_string());
    
    code.globals.push("ADC_HandleTypeDef hadc1;".to_string());
    
    code.init_code.push("__HAL_RCC_ADC1_CLK_ENABLE();".to_string());
    code.init_code.push(format!(
        "hadc1.Instance = ADC1;\nhadc1.Init.ClockPrescaler = ADC_CLOCK_SYNC_PCLK_DIV4;\nhadc1.Init.Resolution = ADC_RESOLUTION_{}_B;\nhadc1.Init.ScanConvMode = DISABLE;\nhadc1.Init.ContinuousConvMode = DISABLE;\nHAL_ADC_Init(&hadc1);",
        resolution
    ));
    
    code.handler_code.push(format!(
        "uint32_t ADC_Read_Channel{}(void) {{\n    ADC_ChannelConfTypeDef cfg = {{ .Channel = ADC_CHANNEL_{}, .Rank = 1, .SamplingTime = ADC_SAMPLETIME_144CYCLES }};\n    HAL_ADC_ConfigChannel(&hadc1, &cfg);\n    HAL_ADC_Start(&hadc1);\n    HAL_ADC_PollForConversion(&hadc1, 100);\n    return HAL_ADC_GetValue(&hadc1);\n}}",
        channel, channel
    ));
    
    code
}

fn generate_dac_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let channel = prop_int(props, "channel", 1);
    
    code.includes.push("<stm32f4xx_hal.h>".to_string());
    code.globals.push("DAC_HandleTypeDef hdac;".to_string());
    
    code.init_code.push("__HAL_RCC_DAC_CLK_ENABLE();".to_string());
    code.init_code.push("hdac.Instance = DAC;".to_string());
    code.init_code.push("HAL_DAC_Init(&hdac);".to_string());
    code.init_code.push(format!(
        "DAC_ChannelConfTypeDef dac_cfg = {{ .DAC_Trigger = DAC_TRIGGER_NONE, .DAC_OutputBuffer = DAC_OUTPUTBUFFER_ENABLE }};\nHAL_DAC_ConfigChannel(&hdac, &dac_cfg, DAC_CHANNEL_{});",
        channel
    ));
    
    code.handler_code.push(format!(
        "void DAC_SetValue_Ch{}(uint32_t value) {{\n    HAL_DAC_SetValue(&hdac, DAC_CHANNEL_{}, DAC_ALIGN_12B_R, value);\n    HAL_DAC_Start(&hdac, DAC_CHANNEL_{});\n}}",
        channel, channel, channel
    ));
    
    code
}

fn generate_pwm_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let timer = prop_int(props, "timer", 1);
    let channel = prop_int(props, "channel", 1);
    let frequency = prop_int(props, "frequency", 1000);
    
    code.includes.push("<stm32f4xx_hal.h>".to_string());
    code.globals.push(format!("TIM_HandleTypeDef htim{};", timer));
    
    let prescaler = 84000000 / (frequency * 1000) - 1;
    
    code.init_code.push(format!(
        "__HAL_RCC_TIM{}_CLK_ENABLE();\nhtim{}.Instance = TIM{};\nhtim{}.Init.Prescaler = {};\nhtim{}.Init.Period = 999;\nhtim{}.Init.CounterMode = TIM_COUNTERMODE_UP;\nHAL_TIM_PWM_Init(&htim{});",
        timer, timer, timer, timer, prescaler, timer, timer, timer
    ));
    
    code.init_code.push(format!(
        "TIM_OC_InitTypeDef oc = {{ .OCMode = TIM_OCMODE_PWM1, .Pulse = 500 }};\nHAL_TIM_PWM_ConfigChannel(&htim{}, &oc, TIM_CHANNEL_{});\nHAL_TIM_PWM_Start(&htim{}, TIM_CHANNEL_{});",
        timer, channel, timer, channel
    ));
    
    code.handler_code.push(format!(
        "void PWM_SetDuty_Tim{}Ch{}(uint16_t duty) {{\n    __HAL_TIM_SET_COMPARE(&htim{}, TIM_CHANNEL_{}, duty);\n}}",
        timer, channel, timer, channel
    ));
    
    code
}

fn generate_uart_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let instance = prop_int(props, "instance", 1);
    let baud = prop_int(props, "baud_rate", 115200);
    
    code.includes.push("<stm32f4xx_hal.h>".to_string());
    code.includes.push("<string.h>".to_string());
    
    code.globals.push(format!("UART_HandleTypeDef huart{};", instance));
    code.globals.push(format!("uint8_t uart{}_rx_buf[256];", instance));
    
    code.init_code.push(format!(
        "__HAL_RCC_USART{}_CLK_ENABLE();\nhuart{}.Instance = USART{};\nhuart{}.Init.BaudRate = {};\nhuart{}.Init.WordLength = UART_WORDLENGTH_8B;\nhuart{}.Init.StopBits = UART_STOPBITS_1;\nhuart{}.Init.Parity = UART_PARITY_NONE;\nhuart{}.Init.Mode = UART_MODE_TX_RX;\nHAL_UART_Init(&huart{});",
        instance, instance, instance, instance, baud, instance, instance, instance, instance, instance
    ));
    
    code.handler_code.push(format!(
        "void UART{}_Send(const char* data) {{\n    HAL_UART_Transmit(&huart{}, (uint8_t*)data, strlen(data), 1000);\n}}",
        instance, instance
    ));
    
    code
}

fn generate_spi_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let instance = prop_int(props, "instance", 1);
    
    code.includes.push("<stm32f4xx_hal.h>".to_string());
    code.globals.push(format!("SPI_HandleTypeDef hspi{};", instance));
    
    code.init_code.push(format!(
        "__HAL_RCC_SPI{}_CLK_ENABLE();\nhspi{}.Instance = SPI{};\nhspi{}.Init.Mode = SPI_MODE_MASTER;\nhspi{}.Init.Direction = SPI_DIRECTION_2LINES;\nhspi{}.Init.DataSize = SPI_DATASIZE_8BIT;\nhspi{}.Init.CLKPolarity = SPI_POLARITY_LOW;\nhspi{}.Init.CLKPhase = SPI_PHASE_1EDGE;\nhspi{}.Init.NSS = SPI_NSS_SOFT;\nHAL_SPI_Init(&hspi{});",
        instance, instance, instance, instance, instance, instance, instance, instance, instance, instance
    ));
    
    code
}

fn generate_i2c_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let instance = prop_int(props, "instance", 1);
    
    code.includes.push("<stm32f4xx_hal.h>".to_string());
    code.globals.push(format!("I2C_HandleTypeDef hi2c{};", instance));
    
    code.init_code.push(format!(
        "__HAL_RCC_I2C{}_CLK_ENABLE();\nhi2c{}.Instance = I2C{};\nhi2c{}.Init.ClockSpeed = 100000;\nhi2c{}.Init.DutyCycle = I2C_DUTYCYCLE_2;\nhi2c{}.Init.OwnAddress1 = 0;\nhi2c{}.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;\nHAL_I2C_Init(&hi2c{});",
        instance, instance, instance, instance, instance, instance, instance, instance
    ));
    
    code
}

fn generate_timer_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let timer = prop_int(props, "timer", 1);
    let period = prop_int(props, "period_ms", 1000);
    
    code.includes.push("<stm32f4xx_hal.h>".to_string());
    code.globals.push(format!("TIM_HandleTypeDef htim{};", timer));
    code.globals.push(format!("volatile uint32_t tim{}_ticks = 0;", timer));
    
    code.init_code.push(format!(
        "__HAL_RCC_TIM{}_CLK_ENABLE();\nhtim{}.Instance = TIM{};\nhtim{}.Init.Prescaler = 8399; // 84MHz/8400 = 10kHz\nhtim{}.Init.Period = {} - 1;\nhtim{}.Init.CounterMode = TIM_COUNTERMODE_UP;\nHAL_TIM_Base_Init(&htim{});\nHAL_TIM_Base_Start_IT(&htim{});",
        timer, timer, timer, timer, timer, period * 10, timer, timer, timer
    ));
    
    code.handler_code.push(format!(
        "void TIM{}_IRQHandler(void) {{\n    HAL_TIM_IRQHandler(&htim{});\n}}\n\nvoid HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {{\n    if (htim->Instance == TIM{}) {{\n        tim{}_ticks++;\n    }}\n}}",
        timer, timer, timer, timer
    ));
    
    code
}

// ============================================================================
// RTOS Node Code Generators
// ============================================================================

fn generate_task_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let name = prop_str(props, "name", "DefaultTask");
    let priority = prop_int(props, "priority", 1);
    let stack = prop_int(props, "stack_size", 256);
    let period_ms = prop_int(props, "period_ms", 100);
    
    code.includes.push("<FreeRTOS.h>".to_string());
    code.includes.push("<task.h>".to_string());
    
    code.globals.push(format!("TaskHandle_t {}Handle;", name));
    
    // Real task implementation with proper timing
    code.handler_code.push(format!(
        "void {}(void *argument) {{\n\
    TickType_t xLastWakeTime = xTaskGetTickCount();\n\
    const TickType_t xFrequency = pdMS_TO_TICKS({});\n\n\
    for(;;) {{\n\
        // ===== Task Logic Start =====\n\
        // Read inputs, process data, update outputs\n\
        // Example: uint32_t sensor_val = ADC_Read();\n\
        // Example: FSM_Process(sensor_val);\n\
        // ===== Task Logic End =====\n\n\
        // Precise periodic timing (better than vTaskDelay)\n\
        vTaskDelayUntil(&xLastWakeTime, xFrequency);\n\
    }}\n}}",
        name, period_ms
    ));
    
    code.init_code.push(format!(
        "xTaskCreate({}, \"{}\", {}, NULL, {}, &{}Handle);",
        name, name, stack, priority, name
    ));
    
    code
}

fn generate_semaphore_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let name = prop_str(props, "name", "sem");
    let sem_type = prop_enum(props, "type", "Binary");
    let initial = prop_int(props, "initial_count", 0);
    
    code.includes.push("<FreeRTOS.h>".to_string());
    code.includes.push("<semphr.h>".to_string());
    
    code.globals.push(format!("SemaphoreHandle_t {};", name));
    
    match sem_type.as_str() {
        "Counting" => {
            let max = prop_int(props, "max_count", 10);
            code.init_code.push(format!(
                "{} = xSemaphoreCreateCounting({}, {});",
                name, max, initial
            ));
        }
        _ => {
            code.init_code.push(format!(
                "{} = xSemaphoreCreateBinary();",
                name
            ));
            if initial > 0 {
                code.init_code.push(format!("xSemaphoreGive({});", name));
            }
        }
    }
    
    code
}

fn generate_mutex_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let name = prop_str(props, "name", "mutex");
    
    code.includes.push("<FreeRTOS.h>".to_string());
    code.includes.push("<semphr.h>".to_string());
    
    code.globals.push(format!("SemaphoreHandle_t {};", name));
    code.init_code.push(format!("{} = xSemaphoreCreateMutex();", name));
    
    code
}

fn generate_queue_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let name = prop_str(props, "name", "queue");
    let length = prop_int(props, "length", 10);
    let item_size = prop_int(props, "item_size", 4);
    
    code.includes.push("<FreeRTOS.h>".to_string());
    code.includes.push("<queue.h>".to_string());
    
    code.globals.push(format!("QueueHandle_t {};", name));
    code.init_code.push(format!(
        "{} = xQueueCreate({}, {});",
        name, length, item_size
    ));
    
    code
}

fn generate_interrupt_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let irq = prop_str(props, "irq_name", "EXTI0");
    let priority = prop_int(props, "priority", 5);
    let pin = prop_int(props, "pin", 0);
    
    code.includes.push("<stm32f4xx_hal.h>".to_string());
    
    // Add volatile flag for ISR-to-task communication
    code.globals.push(format!("volatile uint8_t {}_flag = 0;", irq.to_lowercase()));
    
    code.init_code.push(format!(
        "HAL_NVIC_SetPriority({}_IRQn, {}, 0);\nHAL_NVIC_EnableIRQ({}_IRQn);",
        irq, priority, irq
    ));
    
    // Real interrupt handler with flag clearing and debounce
    code.handler_code.push(format!(
        "void {}_IRQHandler(void) {{\n\
    // Check pending interrupt\n\
    if (__HAL_GPIO_EXTI_GET_IT(GPIO_PIN_{}) != RESET) {{\n\
        __HAL_GPIO_EXTI_CLEAR_IT(GPIO_PIN_{});\n\n\
        // Set flag for main loop / task processing\n\
        {}_flag = 1;\n\n\
        // For RTOS: Signal task from ISR\n\
        // BaseType_t xHigherPriorityTaskWoken = pdFALSE;\n\
        // xSemaphoreGiveFromISR(exti_sem, &xHigherPriorityTaskWoken);\n\
        // portYIELD_FROM_ISR(xHigherPriorityTaskWoken);\n\
    }}\n}}",
        irq, pin, pin, irq.to_lowercase()
    ));
    
    code
}

// ============================================================================
// I/O Node Code Generators
// ============================================================================

fn generate_led_code(props: &HashMap<String, PropertyValue>, ctx: &CodeGenContext) -> GeneratedCode {
    // LED is essentially GPIO output
    let mut mod_props = props.clone();
    mod_props.insert("mode".to_string(), PropertyValue::String("Output".to_string()));
    
    let mut code = generate_gpio_code(&mod_props, ctx);
    
    let port = prop_str(props, "port", "A");
    let pin = prop_int(props, "pin", 0);
    
    code.handler_code.push(format!(
        "void LED_{}_{}_On(void) {{ HAL_GPIO_WritePin(GPIO{}, GPIO_PIN_{}, GPIO_PIN_SET); }}\nvoid LED_{}_{}_Off(void) {{ HAL_GPIO_WritePin(GPIO{}, GPIO_PIN_{}, GPIO_PIN_RESET); }}\nvoid LED_{}_{}_Toggle(void) {{ HAL_GPIO_TogglePin(GPIO{}, GPIO_PIN_{}); }}",
        port, pin, port, pin, port, pin, port, pin, port, pin, port, pin
    ));
    
    code
}

fn generate_button_code(props: &HashMap<String, PropertyValue>, ctx: &CodeGenContext) -> GeneratedCode {
    let mut mod_props = props.clone();
    mod_props.insert("mode".to_string(), PropertyValue::String("Input".to_string()));
    
    let mut code = generate_gpio_code(&mod_props, ctx);
    
    let port = prop_str(props, "port", "A");
    let pin = prop_int(props, "pin", 0);
    let active_low = prop_bool(props, "active_low", false);
    
    let compare = if active_low { "GPIO_PIN_RESET" } else { "GPIO_PIN_SET" };
    
    code.handler_code.push(format!(
        "uint8_t Button_{}_{}_IsPressed(void) {{ return HAL_GPIO_ReadPin(GPIO{}, GPIO_PIN_{}) == {}; }}",
        port, pin, port, pin, compare
    ));
    
    code
}

fn generate_motor_code(props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let name = prop_str(props, "name", "motor1");
    let timer = prop_int(props, "timer", 1);
    let channel = prop_int(props, "channel", 1);
    let dir_port = prop_str(props, "dir_port", "B");
    let dir_pin = prop_int(props, "dir_pin", 0);
    
    code.includes.push("<stm32f4xx_hal.h>".to_string());
    
    // Motor control defines
    code.defines.push(format!("{}_DIR_PORT GPIO{}", name.to_uppercase(), dir_port));
    code.defines.push(format!("{}_DIR_PIN GPIO_PIN_{}", name.to_uppercase(), dir_pin));
    code.defines.push(format!("{}_TIM htim{}", name.to_uppercase(), timer));
    code.defines.push(format!("{}_CHANNEL TIM_CHANNEL_{}", name.to_uppercase(), channel));
    
    // Motor control function with direction and speed
    code.handler_code.push(format!(
        "/**\n\
 * Set motor speed and direction\n\
 * @param speed: -100 to +100 percent (negative = reverse)\n\
 */\n\
void {}_SetSpeed(int16_t speed) {{\n\
    // Clamp speed to valid range\n\
    if (speed > 100) speed = 100;\n\
    if (speed < -100) speed = -100;\n\n\
    // Set direction via H-bridge control pin\n\
    if (speed >= 0) {{\n\
        HAL_GPIO_WritePin({}_DIR_PORT, {}_DIR_PIN, GPIO_PIN_SET);\n\
    }} else {{\n\
        HAL_GPIO_WritePin({}_DIR_PORT, {}_DIR_PIN, GPIO_PIN_RESET);\n\
        speed = -speed; // Use absolute value for duty\n\
    }}\n\n\
    // Map 0-100% to PWM range (0-999 for 1kHz PWM with period 999)\n\
    uint16_t duty = (uint16_t)((speed * 999) / 100);\n\
    __HAL_TIM_SET_COMPARE(&{}_TIM, {}_CHANNEL, duty);\n}}",
        name, 
        name.to_uppercase(), name.to_uppercase(),
        name.to_uppercase(), name.to_uppercase(),
        name.to_uppercase(), name.to_uppercase()
    ));
    
    // Brake function
    code.handler_code.push(format!(
        "/**\n\
 * Stop motor (set PWM to 0)\n\
 */\n\
void {}_Stop(void) {{\n\
    __HAL_TIM_SET_COMPARE(&{}_TIM, {}_CHANNEL, 0);\n}}",
        name, name.to_uppercase(), name.to_uppercase()
    ));
    
    code
}

// ============================================================================
// FSM Node Code Generators
// ============================================================================

fn generate_state_code(node_type: &NodeType, props: &HashMap<String, PropertyValue>, _ctx: &CodeGenContext) -> GeneratedCode {
    let mut code = GeneratedCode::new();
    
    let name = prop_str(props, "name", "State");
    
    // Generate state enum value
    match node_type {
        NodeType::Initial => {
            code.types.push(format!("// Initial state: {}", name));
        }
        NodeType::Final => {
            code.types.push(format!("// Final state: {}", name));
        }
        NodeType::State => {
            code.types.push(format!("// State: {}", name));
        }
        _ => {}
    }
    
    code
}

// ============================================================================
// Property Helpers
// ============================================================================

fn prop_str(props: &HashMap<String, PropertyValue>, key: &str, default: &str) -> String {
    match props.get(key) {
        Some(PropertyValue::String(s)) => s.clone(),
        _ => default.to_string(),
    }
}

fn prop_int(props: &HashMap<String, PropertyValue>, key: &str, default: i64) -> i64 {
    match props.get(key) {
        Some(PropertyValue::Integer(n)) => *n,
        _ => default,
    }
}

fn prop_bool(props: &HashMap<String, PropertyValue>, key: &str, default: bool) -> bool {
    match props.get(key) {
        Some(PropertyValue::Boolean(b)) => *b,
        _ => default,
    }
}

fn prop_enum(props: &HashMap<String, PropertyValue>, key: &str, default: &str) -> String {
    match props.get(key) {
        Some(PropertyValue::Enum { value, .. }) => value.clone(),
        _ => default.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_gpio_codegen() {
        let mut props = HashMap::new();
        props.insert("port".to_string(), PropertyValue::String("B".to_string()));
        props.insert("pin".to_string(), PropertyValue::Integer(13));
        props.insert("mode".to_string(), PropertyValue::Enum { 
            value: "Output".to_string(), 
            options: vec!["Input".to_string(), "Output".to_string()] 
        });
        
        let ctx = CodeGenContext::default();
        let code = generate_gpio_code(&props, &ctx);
        
        assert!(!code.includes.is_empty());
        assert!(!code.init_code.is_empty());
    }
    
    #[test]
    fn test_task_codegen() {
        let mut props = HashMap::new();
        props.insert("name".to_string(), PropertyValue::String("SensorTask".to_string()));
        props.insert("priority".to_string(), PropertyValue::Integer(2));
        props.insert("stack_size".to_string(), PropertyValue::Integer(512));
        
        let ctx = CodeGenContext::default();
        let code = generate_task_code(&props, &ctx);
        
        assert!(code.includes.iter().any(|i| i.contains("FreeRTOS")));
        assert!(code.globals.iter().any(|g| g.contains("SensorTask")));
    }
}
